//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SageConnector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SageConnector.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow32x16 {
            get {
                object obj = ResourceManager.GetObject("arrow32x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In-Progress Request Cancellation.
        /// </summary>
        internal static string CancelInProgress_Caption {
            get {
                return ResourceManager.GetString("CancelInProgress_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current in-progress request for this site will be removed. Your site contacts must make a new request if they want to complete it. Do you want to continue?.
        /// </summary>
        internal static string CancelInProgress_Message {
            get {
                return ResourceManager.GetString("CancelInProgress_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected account does not have the permissions needed for the service. Please modify the account to have the appropriate permissions, or select a different account. For more information regarding user account permissions, see Help..
        /// </summary>
        internal static string ConnectorAccountSelection_AccountSelectionAccessErrorText {
            get {
                return ResourceManager.GetString("ConnectorAccountSelection_AccountSelectionAccessErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Selection Error.
        /// </summary>
        internal static string ConnectorAccountSelection_AccountSelectionErrorCaption {
            get {
                return ResourceManager.GetString("ConnectorAccountSelection_AccountSelectionErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account or password is invalid..
        /// </summary>
        internal static string ConnectorAccountSelection_AccountSelectionErrorText {
            get {
                return ResourceManager.GetString("ConnectorAccountSelection_AccountSelectionErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a password..
        /// </summary>
        internal static string ConnectorAccountSelection_MissingPasswordText {
            get {
                return ResourceManager.GetString("ConnectorAccountSelection_MissingPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a user name..
        /// </summary>
        internal static string ConnectorAccountSelection_MissingUserText {
            get {
                return ResourceManager.GetString("ConnectorAccountSelection_MissingUserText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords do not match.  Please re-enter the passwords..
        /// </summary>
        internal static string ConnectorAccountSelection_PasswordsNotEqualText {
            get {
                return ResourceManager.GetString("ConnectorAccountSelection_PasswordsNotEqualText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Windows account to use with the {0}..
        /// </summary>
        internal static string ConnectorAccountSelection_SelectionText {
            get {
                return ResourceManager.GetString("ConnectorAccountSelection_SelectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which option should I choose?.
        /// </summary>
        internal static string ConnectorAccountSelectionForm_HelpLinkText {
            get {
                return ResourceManager.GetString("ConnectorAccountSelectionForm_HelpLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (not available for this operating system).
        /// </summary>
        internal static string ConnectorAccountSelectionForm_StockAccountNotAvailableText {
            get {
                return ResourceManager.GetString("ConnectorAccountSelectionForm_StockAccountNotAvailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Required.
        /// </summary>
        internal static string ConnectorBackofficeUpdateRequired_Caption {
            get {
                return ResourceManager.GetString("ConnectorBackofficeUpdateRequired_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The back office software is not current. Please update your back office software..
        /// </summary>
        internal static string ConnectorBackofficeUpdateRequired_Message {
            get {
                return ResourceManager.GetString("ConnectorBackofficeUpdateRequired_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data access problem has occurred..
        /// </summary>
        internal static string ConnectorCommon_ConfigurationDataProblem {
            get {
                return ResourceManager.GetString("ConnectorCommon_ConfigurationDataProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occurred.
        /// </summary>
        internal static string ConnectorCommon_ErrorCaption {
            get {
                return ResourceManager.GetString("ConnectorCommon_ErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Connection Change.
        /// </summary>
        internal static string ConnectorDetails_AreYouSureYouWantToUpdateCaption {
            get {
                return ResourceManager.GetString("ConnectorDetails_AreYouSureYouWantToUpdateCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Making this change will significantly alter the existing connection between the back office and the Sage site.  You are creating a new link between this database and the site, which permanently removes the existing link. Are you sure you want to continue?.
        /// </summary>
        internal static string ConnectorDetails_AreYouSureYouWantToUpdateMessage {
            get {
                return ResourceManager.GetString("ConnectorDetails_AreYouSureYouWantToUpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} connection details.
        /// </summary>
        internal static string ConnectorDetails_BackofficeDetailsHeader {
            get {
                return ResourceManager.GetString("ConnectorDetails_BackofficeDetailsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string ConnectorDetails_ButtonCancel {
            get {
                return ResourceManager.GetString("ConnectorDetails_ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        internal static string ConnectorDetails_ButtonSave {
            get {
                return ResourceManager.GetString("ConnectorDetails_ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Connection.
        /// </summary>
        internal static string ConnectorDetails_ButtonTestConnection {
            get {
                return ResourceManager.GetString("ConnectorDetails_ButtonTestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are issues with this connection that will prevent it from functioning properly.  Do you want to save it anyway?{0}{1}{2}.
        /// </summary>
        internal static string ConnectorDetails_CompleteConnectionIssue_Message {
            get {
                return ResourceManager.GetString("ConnectorDetails_CompleteConnectionIssue_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Error.
        /// </summary>
        internal static string ConnectorDetails_ConfigurationErrorCaption {
            get {
                return ResourceManager.GetString("ConnectorDetails_ConfigurationErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Issues.
        /// </summary>
        internal static string ConnectorDetails_ConnectionIssues_Caption {
            get {
                return ResourceManager.GetString("ConnectorDetails_ConnectionIssues_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Status.
        /// </summary>
        internal static string ConnectorDetails_ConnectionStatusCaption {
            get {
                return ResourceManager.GetString("ConnectorDetails_ConnectionStatusCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection successful..
        /// </summary>
        internal static string ConnectorDetails_ConnectionStatusOk {
            get {
                return ResourceManager.GetString("ConnectorDetails_ConnectionStatusOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error initializing new connection:{0}{1}.
        /// </summary>
        internal static string ConnectorDetails_ErrorInitializingForAddTenant {
            get {
                return ResourceManager.GetString("ConnectorDetails_ErrorInitializingForAddTenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error validating the active connection. {0}{1}.
        /// </summary>
        internal static string ConnectorDetails_ErrorValidatingTenantConnection {
            get {
                return ResourceManager.GetString("ConnectorDetails_ErrorValidatingTenantConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error validating website identification..
        /// </summary>
        internal static string ConnectorDetails_ErrorValidatingTenantId {
            get {
                return ResourceManager.GetString("ConnectorDetails_ErrorValidatingTenantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Connection Details.
        /// </summary>
        internal static string ConnectorDetails_FormTitle {
            get {
                return ResourceManager.GetString("ConnectorDetails_FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name:.
        /// </summary>
        internal static string ConnectorDetails_LabelBackofficeCompanyName {
            get {
                return ResourceManager.GetString("ConnectorDetails_LabelBackofficeCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection key:.
        /// </summary>
        internal static string ConnectorDetails_LabelConnectionKey {
            get {
                return ResourceManager.GetString("ConnectorDetails_LabelConnectionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data connection:.
        /// </summary>
        internal static string ConnectorDetails_LabelDatabasePath {
            get {
                return ResourceManager.GetString("ConnectorDetails_LabelDatabasePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable connection:.
        /// </summary>
        internal static string ConnectorDetails_LabelEnableConnection {
            get {
                return ResourceManager.GetString("ConnectorDetails_LabelEnableConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gateway address:.
        /// </summary>
        internal static string ConnectorDetails_LabelEnpointAddress {
            get {
                return ResourceManager.GetString("ConnectorDetails_LabelEnpointAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string ConnectorDetails_LabelPassword {
            get {
                return ResourceManager.GetString("ConnectorDetails_LabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site address:.
        /// </summary>
        internal static string ConnectorDetails_LabelSiteURL {
            get {
                return ResourceManager.GetString("ConnectorDetails_LabelSiteURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name:.
        /// </summary>
        internal static string ConnectorDetails_LabelTenantCompanyName {
            get {
                return ResourceManager.GetString("ConnectorDetails_LabelTenantCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID:.
        /// </summary>
        internal static string ConnectorDetails_LabelUserId {
            get {
                return ResourceManager.GetString("ConnectorDetails_LabelUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back office connection was not successful..
        /// </summary>
        internal static string ConnectorDetails_PremiseConnectionStatusNotOk {
            get {
                return ResourceManager.GetString("ConnectorDetails_PremiseConnectionStatusNotOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Error.
        /// </summary>
        internal static string ConnectorDetails_SaveFailedCaption {
            get {
                return ResourceManager.GetString("ConnectorDetails_SaveFailedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save failed with message: {0}{1}.
        /// </summary>
        internal static string ConnectorDetails_SaveFailedMessage {
            get {
                return ResourceManager.GetString("ConnectorDetails_SaveFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to the website was not successful..
        /// </summary>
        internal static string ConnectorDetails_TenantConnectionStatusNotOk {
            get {
                return ResourceManager.GetString("ConnectorDetails_TenantConnectionStatusNotOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} connection details.
        /// </summary>
        internal static string ConnectorDetails_TenantDetailsHeader {
            get {
                return ResourceManager.GetString("ConnectorDetails_TenantDetailsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string ConnectorLogin_ConfirmDeleteCaption {
            get {
                return ResourceManager.GetString("ConnectorLogin_ConfirmDeleteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this connection?.
        /// </summary>
        internal static string ConnectorLogin_ConfirmDeleteMessage {
            get {
                return ResourceManager.GetString("ConnectorLogin_ConfirmDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Deleting.
        /// </summary>
        internal static string ConnectorLogin_DeleteFailedCaption {
            get {
                return ResourceManager.GetString("ConnectorLogin_DeleteFailedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion failed with message: {0}{1}.
        /// </summary>
        internal static string ConnectorLogin_DeleteFailedMessage {
            get {
                return ResourceManager.GetString("ConnectorLogin_DeleteFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Login.
        /// </summary>
        internal static string ConnectorLogin_DialogTitle {
            get {
                return ResourceManager.GetString("ConnectorLogin_DialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Error.
        /// </summary>
        internal static string ConnectorLogin_LoginErrorCaption {
            get {
                return ResourceManager.GetString("ConnectorLogin_LoginErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to login: {0}{1}.
        /// </summary>
        internal static string ConnectorLogin_LoginErrorMessage {
            get {
                return ResourceManager.GetString("ConnectorLogin_LoginErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed..
        /// </summary>
        internal static string ConnectorLogin_LogonFailed {
            get {
                return ResourceManager.GetString("ConnectorLogin_LogonFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No response received from the back office.
        /// </summary>
        internal static string ConnectorLogin_NoResponseFromBackoffice {
            get {
                return ResourceManager.GetString("ConnectorLogin_NoResponseFromBackoffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name or password is incorrect..
        /// </summary>
        internal static string ConnectorLogin_PasswordIncorrect {
            get {
                return ResourceManager.GetString("ConnectorLogin_PasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the User ID and Password for the {0} {1}..
        /// </summary>
        internal static string ConnectorLogon_Instructions {
            get {
                return ResourceManager.GetString("ConnectorLogon_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the Password of the {0} {1} account for the company database you want to use..
        /// </summary>
        internal static string ConnectorLogon_Instructions_PerCompanyAdministrator_AccountReadOnly {
            get {
                return ResourceManager.GetString("ConnectorLogon_Instructions_PerCompanyAdministrator_AccountReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} company.
        /// </summary>
        internal static string ConnectorMain_BackofficeColumnHeader {
            get {
                return ResourceManager.GetString("ConnectorMain_BackofficeColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Add.
        /// </summary>
        internal static string ConnectorMain_ButtonAdd {
            get {
                return ResourceManager.GetString("ConnectorMain_ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close.
        /// </summary>
        internal static string ConnectorMain_ButtonClose {
            get {
                return ResourceManager.GetString("ConnectorMain_ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete.
        /// </summary>
        internal static string ConnectorMain_ButtonDelete {
            get {
                return ResourceManager.GetString("ConnectorMain_ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit.
        /// </summary>
        internal static string ConnectorMain_ButtonEdit {
            get {
                return ResourceManager.GetString("ConnectorMain_ButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Test All Connections.
        /// </summary>
        internal static string ConnectorMain_ButtonTestAllConnections {
            get {
                return ResourceManager.GetString("ConnectorMain_ButtonTestAllConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string ConnectorMain_ColumnHeaderActive {
            get {
                return ResourceManager.GetString("ConnectorMain_ColumnHeaderActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Company.
        /// </summary>
        internal static string ConnectorMain_CompanyColumnHeader {
            get {
                return ResourceManager.GetString("ConnectorMain_CompanyColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating list of connections with message: {0}{1}.
        /// </summary>
        internal static string ConnectorMain_ErrorRefreshingConnectionList {
            get {
                return ResourceManager.GetString("ConnectorMain_ErrorRefreshingConnectionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Updating Connection Status.
        /// </summary>
        internal static string ConnectorMain_ErrorUpdatingActiveStatusCaption {
            get {
                return ResourceManager.GetString("ConnectorMain_ErrorUpdatingActiveStatusCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update all connection statuses.{0}.
        /// </summary>
        internal static string ConnectorMain_ErrorUpdatingActiveStatusMessages {
            get {
                return ResourceManager.GetString("ConnectorMain_ErrorUpdatingActiveStatusMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Connector.
        /// </summary>
        internal static string ConnectorMain_FormName {
            get {
                return ResourceManager.GetString("ConnectorMain_FormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} connection details.
        /// </summary>
        internal static string ConnectorMain_GrpBoxLabelBackofficeConnectionDetails {
            get {
                return ResourceManager.GetString("ConnectorMain_GrpBoxLabelBackofficeConnectionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sage connection details.
        /// </summary>
        internal static string ConnectorMain_GrpBoxLabelTenantConnectionDetails {
            get {
                return ResourceManager.GetString("ConnectorMain_GrpBoxLabelTenantConnectionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name:.
        /// </summary>
        internal static string ConnectorMain_LabelCompanyName {
            get {
                return ResourceManager.GetString("ConnectorMain_LabelCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Enabled:.
        /// </summary>
        internal static string ConnectorMain_LabelConnectionEnabled {
            get {
                return ResourceManager.GetString("ConnectorMain_LabelConnectionEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Log.
        /// </summary>
        internal static string ConnectorMain_LabelConnectionLog {
            get {
                return ResourceManager.GetString("ConnectorMain_LabelConnectionLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data connection:.
        /// </summary>
        internal static string ConnectorMain_LabelDatabasePath {
            get {
                return ResourceManager.GetString("ConnectorMain_LabelDatabasePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Successful Connection - Date/Time.
        /// </summary>
        internal static string ConnectorMain_LabelLastConnection {
            get {
                return ResourceManager.GetString("ConnectorMain_LabelLastConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sage Connections.
        /// </summary>
        internal static string ConnectorMain_LabelSageSkyfireConnections {
            get {
                return ResourceManager.GetString("ConnectorMain_LabelSageSkyfireConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website:.
        /// </summary>
        internal static string ConnectorMain_LabelSiteUrl {
            get {
                return ResourceManager.GetString("ConnectorMain_LabelSiteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string ConnectorMain_LabelVersion {
            get {
                return ResourceManager.GetString("ConnectorMain_LabelVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} update required.
        /// </summary>
        internal static string ConnectorMain_LinkBackOfficeUpdateRequired {
            get {
                return ResourceManager.GetString("ConnectorMain_LinkBackOfficeUpdateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connector update available.
        /// </summary>
        internal static string ConnectorMain_LinkConnectorUpdateAvailable {
            get {
                return ResourceManager.GetString("ConnectorMain_LinkConnectorUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connector update required.
        /// </summary>
        internal static string ConnectorMain_LinkConnectorUpdateRequired {
            get {
                return ResourceManager.GetString("ConnectorMain_LinkConnectorUpdateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify the {0} service is running and start {1} again..
        /// </summary>
        internal static string ConnectorMain_ServiceIsNotRunningErrorMessage {
            get {
                return ResourceManager.GetString("ConnectorMain_ServiceIsNotRunningErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {3} [{1} {2}].
        /// </summary>
        internal static string ConnectorMain_SystemMessageListBoxRow {
            get {
                return ResourceManager.GetString("ConnectorMain_SystemMessageListBoxRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back office company name:.
        /// </summary>
        internal static string ConnectorRequestList_BackofficeCompanyNameLabel {
            get {
                return ResourceManager.GetString("ConnectorRequestList_BackofficeCompanyNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close.
        /// </summary>
        internal static string ConnectorRequestList_Close {
            get {
                return ResourceManager.GetString("ConnectorRequestList_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name: .
        /// </summary>
        internal static string ConnectorRequestList_CloudCompanyNameLabel {
            get {
                return ResourceManager.GetString("ConnectorRequestList_CloudCompanyNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name.
        /// </summary>
        internal static string ConnectorRequestList_ColumnProjectNameTitle {
            get {
                return ResourceManager.GetString("ConnectorRequestList_ColumnProjectNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested by.
        /// </summary>
        internal static string ConnectorRequestList_ColumnRequestedByTitle {
            get {
                return ResourceManager.GetString("ConnectorRequestList_ColumnRequestedByTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string ConnectorRequestList_ColumnRequestStatusImageTitle {
            get {
                return ResourceManager.GetString("ConnectorRequestList_ColumnRequestStatusImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string ConnectorRequestList_ColumnRequestStatusTitle {
            get {
                return ResourceManager.GetString("ConnectorRequestList_ColumnRequestStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string ConnectorRequestList_ColumnRequestSummeryTitle {
            get {
                return ResourceManager.GetString("ConnectorRequestList_ColumnRequestSummeryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed time.
        /// </summary>
        internal static string ConnectorRequestList_ColumnRequestTimeElapsedTitle {
            get {
                return ResourceManager.GetString("ConnectorRequestList_ColumnRequestTimeElapsedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string ConnectorRequestList_ColumnRequestTypeTitle {
            get {
                return ResourceManager.GetString("ConnectorRequestList_ColumnRequestTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started on.
        /// </summary>
        internal static string ConnectorRequestList_ColumnTimeRequestedTitle {
            get {
                return ResourceManager.GetString("ConnectorRequestList_ColumnTimeRequestedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string ConnectorRequestList_ConfirmDialogCaption {
            get {
                return ResourceManager.GetString("ConnectorRequestList_ConfirmDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel the {0} selected request(s)?.
        /// </summary>
        internal static string ConnectorRequestList_ConfirmDialogMessage {
            get {
                return ResourceManager.GetString("ConnectorRequestList_ConfirmDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cance&amp;l request(s).
        /// </summary>
        internal static string ConnectorRequestList_DeleteButton {
            get {
                return ResourceManager.GetString("ConnectorRequestList_DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sage In-Progress Requests.
        /// </summary>
        internal static string ConnectorRequestList_DialogCaption {
            get {
                return ResourceManager.GetString("ConnectorRequestList_DialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occured:.
        /// </summary>
        internal static string ConnectorRequestList_ErrorDeleteingCaption {
            get {
                return ResourceManager.GetString("ConnectorRequestList_ErrorDeleteingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to cancel request(s) - {0}{1}.
        /// </summary>
        internal static string ConnectorRequestList_ErrorDeletingText {
            get {
                return ResourceManager.GetString("ConnectorRequestList_ErrorDeletingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured:.
        /// </summary>
        internal static string ConnectorRequestList_ErrorMessageCaption {
            get {
                return ResourceManager.GetString("ConnectorRequestList_ErrorMessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to access request data.
        /// </summary>
        internal static string ConnectorRequestList_ErrorMessageText {
            get {
                return ResourceManager.GetString("ConnectorRequestList_ErrorMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest refresh:  .
        /// </summary>
        internal static string ConnectorRequestList_LastRefreshLabelText {
            get {
                return ResourceManager.GetString("ConnectorRequestList_LastRefreshLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Refresh.
        /// </summary>
        internal static string ConnectorRequestList_RefreshButton {
            get {
                return ResourceManager.GetString("ConnectorRequestList_RefreshButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Error.
        /// </summary>
        internal static string ConnectorServiceNotReady_ConfigureErrorCaption {
            get {
                return ResourceManager.GetString("ConnectorServiceNotReady_ConfigureErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem configuring the service.  Refer to the Windows Event Viewer for more information..
        /// </summary>
        internal static string ConnectorServiceNotReady_ConfigureErrorText {
            get {
                return ResourceManager.GetString("ConnectorServiceNotReady_ConfigureErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} service is not currently configured and running on this computer.
        ///
        ///You must first complete this activity to begin using the {1}..
        /// </summary>
        internal static string ConnectorServiceNotReady_NotConfiguredText {
            get {
                return ResourceManager.GetString("ConnectorServiceNotReady_NotConfiguredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} service is not currently running on this computer.
        ///
        ///{1}Select Start to start the service using the current configuration.
        ///{1}Select Reconfigure if you want to change the configuration prior to 
        ///  starting the service (for example, to change account information)..
        /// </summary>
        internal static string ConnectorServiceNotReady_NotRunningText {
            get {
                return ResourceManager.GetString("ConnectorServiceNotReady_NotRunningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Not Responding.
        /// </summary>
        internal static string ConnectorServiceNotReady_WaitForServiceErrorCaption {
            get {
                return ResourceManager.GetString("ConnectorServiceNotReady_WaitForServiceErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service is taking longer than expected to start. Try starting the service again (by starting the {0} software or by reconfiguring the service account). If you continue to receive this message, please contact customer support..
        /// </summary>
        internal static string ConnectorServiceNotReady_WaitForServiceErrorText {
            get {
                return ResourceManager.GetString("ConnectorServiceNotReady_WaitForServiceErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connector Update Available.
        /// </summary>
        internal static string ConnectorSimpleConnectorUpdateAvailable_Caption {
            get {
                return ResourceManager.GetString("ConnectorSimpleConnectorUpdateAvailable_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update for the Sage Connector is available. You can continue to use your existing version and can choose to perform the update when it is convenient for you..
        /// </summary>
        internal static string ConnectorSimpleConnectorUpdateAvailable_Message {
            get {
                return ResourceManager.GetString("ConnectorSimpleConnectorUpdateAvailable_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connector Update Required.
        /// </summary>
        internal static string ConnectorSimpleConnectorUpdateRequired_Caption {
            get {
                return ResourceManager.GetString("ConnectorSimpleConnectorUpdateRequired_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update for the Sage Connector is required. You must update your existing version to continue to use the connector..
        /// </summary>
        internal static string ConnectorSimpleConnectorUpdateRequired_Message {
            get {
                return ResourceManager.GetString("ConnectorSimpleConnectorUpdateRequired_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0} was made available on {2}. {5}{3}.
        /// </summary>
        internal static string ConnectorUpdateFormUpdateAvailable_Message {
            get {
                return ResourceManager.GetString("ConnectorUpdateFormUpdateAvailable_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update to the connector is available.{5}{3}.
        /// </summary>
        internal static string ConnectorUpdateFormUpdateAvailableNoVersion_Message {
            get {
                return ResourceManager.GetString("ConnectorUpdateFormUpdateAvailableNoVersion_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0} was made available on {2}. {5}{3}.
        /// </summary>
        internal static string ConnectorUpdateFormUpdateRequired_Message {
            get {
                return ResourceManager.GetString("ConnectorUpdateFormUpdateRequired_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update to the connector is required.{5}{3}.
        /// </summary>
        internal static string ConnectorUpdateFormUpdateRequiredNoVersion_Message {
            get {
                return ResourceManager.GetString("ConnectorUpdateFormUpdateRequiredNoVersion_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_config_error {
            get {
                object obj = ResourceManager.GetObject("Image_config_error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_edit_configuration {
            get {
                object obj = ResourceManager.GetObject("Image_edit_configuration", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_new_service {
            get {
                object obj = ResourceManager.GetObject("Image_new_service", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Image_service_stopped {
            get {
                object obj = ResourceManager.GetObject("Image_service_stopped", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Installer {
            get {
                object obj = ResourceManager.GetObject("Installer", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap selelection_up {
            get {
                object obj = ResourceManager.GetObject("selelection_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
