//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("LogStoreModel", "ActivityEntryLogEntry", "ActivityEntry", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Sage.Connector.PremiseStore.LogStore.ActivityEntry), "LogEntry", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Sage.Connector.PremiseStore.LogStore.LogEntry))]

#endregion

namespace Sage.Connector.PremiseStore.LogStore
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    internal partial class LogStoreModelContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new LogStoreModelContainer object using the connection string found in the 'LogStoreModelContainer' section of the application configuration file.
        /// </summary>
        public LogStoreModelContainer() : base("name=LogStoreModelContainer", "LogStoreModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LogStoreModelContainer object.
        /// </summary>
        public LogStoreModelContainer(string connectionString) : base(connectionString, "LogStoreModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LogStoreModelContainer object.
        /// </summary>
        public LogStoreModelContainer(EntityConnection connection) : base(connection, "LogStoreModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LogEntry> LogEntries
        {
            get
            {
                if ((_LogEntries == null))
                {
                    _LogEntries = base.CreateObjectSet<LogEntry>("LogEntries");
                }
                return _LogEntries;
            }
        }
        private ObjectSet<LogEntry> _LogEntries;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ActivityEntry> ActivityEntries
        {
            get
            {
                if ((_ActivityEntries == null))
                {
                    _ActivityEntries = base.CreateObjectSet<ActivityEntry>("ActivityEntries");
                }
                return _ActivityEntries;
            }
        }
        private ObjectSet<ActivityEntry> _ActivityEntries;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LogEntries EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLogEntries(LogEntry logEntry)
        {
            base.AddObject("LogEntries", logEntry);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ActivityEntries EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToActivityEntries(ActivityEntry activityEntry)
        {
            base.AddObject("ActivityEntries", activityEntry);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LogStoreModel", Name="ActivityEntry")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ActivityEntry : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ActivityEntry object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="cloudTenantId">Initial value of the CloudTenantId property.</param>
        /// <param name="cloudRequestId">Initial value of the CloudRequestId property.</param>
        /// <param name="cloudRequestType">Initial value of the CloudRequestType property.</param>
        /// <param name="cloudRequestCreatedTimestampUtc">Initial value of the CloudRequestCreatedTimestampUtc property.</param>
        /// <param name="cloudRequestRequestingUser">Initial value of the CloudRequestRequestingUser property.</param>
        /// <param name="cloudRequestRetryCount">Initial value of the CloudRequestRetryCount property.</param>
        /// <param name="isSystemRequest">Initial value of the IsSystemRequest property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        /// <param name="dateTimeUtc">Initial value of the DateTimeUtc property.</param>
        public static ActivityEntry CreateActivityEntry(global::System.Guid id, global::System.String cloudTenantId, global::System.Guid cloudRequestId, global::System.String cloudRequestType, global::System.DateTime cloudRequestCreatedTimestampUtc, global::System.String cloudRequestRequestingUser, global::System.Int64 cloudRequestRetryCount, global::System.Boolean isSystemRequest, global::System.Int32 status, global::System.DateTime dateTimeUtc)
        {
            ActivityEntry activityEntry = new ActivityEntry();
            activityEntry.Id = id;
            activityEntry.CloudTenantId = cloudTenantId;
            activityEntry.CloudRequestId = cloudRequestId;
            activityEntry.CloudRequestType = cloudRequestType;
            activityEntry.CloudRequestCreatedTimestampUtc = cloudRequestCreatedTimestampUtc;
            activityEntry.CloudRequestRequestingUser = cloudRequestRequestingUser;
            activityEntry.CloudRequestRetryCount = cloudRequestRetryCount;
            activityEntry.IsSystemRequest = isSystemRequest;
            activityEntry.Status = status;
            activityEntry.DateTimeUtc = dateTimeUtc;
            return activityEntry;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CloudTenantId
        {
            get
            {
                return _CloudTenantId;
            }
            set
            {
                OnCloudTenantIdChanging(value);
                ReportPropertyChanging("CloudTenantId");
                _CloudTenantId = StructuralObject.SetValidValue(value, false, "CloudTenantId");
                ReportPropertyChanged("CloudTenantId");
                OnCloudTenantIdChanged();
            }
        }
        private global::System.String _CloudTenantId;
        partial void OnCloudTenantIdChanging(global::System.String value);
        partial void OnCloudTenantIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid CloudRequestId
        {
            get
            {
                return _CloudRequestId;
            }
            set
            {
                OnCloudRequestIdChanging(value);
                ReportPropertyChanging("CloudRequestId");
                _CloudRequestId = StructuralObject.SetValidValue(value, "CloudRequestId");
                ReportPropertyChanged("CloudRequestId");
                OnCloudRequestIdChanged();
            }
        }
        private global::System.Guid _CloudRequestId;
        partial void OnCloudRequestIdChanging(global::System.Guid value);
        partial void OnCloudRequestIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CloudRequestType
        {
            get
            {
                return _CloudRequestType;
            }
            set
            {
                OnCloudRequestTypeChanging(value);
                ReportPropertyChanging("CloudRequestType");
                _CloudRequestType = StructuralObject.SetValidValue(value, false, "CloudRequestType");
                ReportPropertyChanged("CloudRequestType");
                OnCloudRequestTypeChanged();
            }
        }
        private global::System.String _CloudRequestType;
        partial void OnCloudRequestTypeChanging(global::System.String value);
        partial void OnCloudRequestTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CloudRequestInnerType
        {
            get
            {
                return _CloudRequestInnerType;
            }
            set
            {
                OnCloudRequestInnerTypeChanging(value);
                ReportPropertyChanging("CloudRequestInnerType");
                _CloudRequestInnerType = StructuralObject.SetValidValue(value, true, "CloudRequestInnerType");
                ReportPropertyChanged("CloudRequestInnerType");
                OnCloudRequestInnerTypeChanged();
            }
        }
        private global::System.String _CloudRequestInnerType;
        partial void OnCloudRequestInnerTypeChanging(global::System.String value);
        partial void OnCloudRequestInnerTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CloudRequestCreatedTimestampUtc
        {
            get
            {
                return _CloudRequestCreatedTimestampUtc;
            }
            set
            {
                OnCloudRequestCreatedTimestampUtcChanging(value);
                ReportPropertyChanging("CloudRequestCreatedTimestampUtc");
                _CloudRequestCreatedTimestampUtc = StructuralObject.SetValidValue(value, "CloudRequestCreatedTimestampUtc");
                ReportPropertyChanged("CloudRequestCreatedTimestampUtc");
                OnCloudRequestCreatedTimestampUtcChanged();
            }
        }
        private global::System.DateTime _CloudRequestCreatedTimestampUtc;
        partial void OnCloudRequestCreatedTimestampUtcChanging(global::System.DateTime value);
        partial void OnCloudRequestCreatedTimestampUtcChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CloudProjectName
        {
            get
            {
                return _CloudProjectName;
            }
            set
            {
                OnCloudProjectNameChanging(value);
                ReportPropertyChanging("CloudProjectName");
                _CloudProjectName = StructuralObject.SetValidValue(value, true, "CloudProjectName");
                ReportPropertyChanged("CloudProjectName");
                OnCloudProjectNameChanged();
            }
        }
        private global::System.String _CloudProjectName;
        partial void OnCloudProjectNameChanging(global::System.String value);
        partial void OnCloudProjectNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CloudRequestRequestingUser
        {
            get
            {
                return _CloudRequestRequestingUser;
            }
            set
            {
                OnCloudRequestRequestingUserChanging(value);
                ReportPropertyChanging("CloudRequestRequestingUser");
                _CloudRequestRequestingUser = StructuralObject.SetValidValue(value, false, "CloudRequestRequestingUser");
                ReportPropertyChanged("CloudRequestRequestingUser");
                OnCloudRequestRequestingUserChanged();
            }
        }
        private global::System.String _CloudRequestRequestingUser;
        partial void OnCloudRequestRequestingUserChanging(global::System.String value);
        partial void OnCloudRequestRequestingUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CloudRequestSummary
        {
            get
            {
                return _CloudRequestSummary;
            }
            set
            {
                OnCloudRequestSummaryChanging(value);
                ReportPropertyChanging("CloudRequestSummary");
                _CloudRequestSummary = StructuralObject.SetValidValue(value, true, "CloudRequestSummary");
                ReportPropertyChanged("CloudRequestSummary");
                OnCloudRequestSummaryChanged();
            }
        }
        private global::System.String _CloudRequestSummary;
        partial void OnCloudRequestSummaryChanging(global::System.String value);
        partial void OnCloudRequestSummaryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 CloudRequestRetryCount
        {
            get
            {
                return _CloudRequestRetryCount;
            }
            set
            {
                OnCloudRequestRetryCountChanging(value);
                ReportPropertyChanging("CloudRequestRetryCount");
                _CloudRequestRetryCount = StructuralObject.SetValidValue(value, "CloudRequestRetryCount");
                ReportPropertyChanged("CloudRequestRetryCount");
                OnCloudRequestRetryCountChanged();
            }
        }
        private global::System.Int64 _CloudRequestRetryCount;
        partial void OnCloudRequestRetryCountChanging(global::System.Int64 value);
        partial void OnCloudRequestRetryCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsSystemRequest
        {
            get
            {
                return _IsSystemRequest;
            }
            set
            {
                OnIsSystemRequestChanging(value);
                ReportPropertyChanging("IsSystemRequest");
                _IsSystemRequest = StructuralObject.SetValidValue(value, "IsSystemRequest");
                ReportPropertyChanged("IsSystemRequest");
                OnIsSystemRequestChanged();
            }
        }
        private global::System.Boolean _IsSystemRequest;
        partial void OnIsSystemRequestChanging(global::System.Boolean value);
        partial void OnIsSystemRequestChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, "Status");
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.Int32 _Status;
        partial void OnStatusChanging(global::System.Int32 value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> State1DateTimeUtc
        {
            get
            {
                return _State1DateTimeUtc;
            }
            set
            {
                OnState1DateTimeUtcChanging(value);
                ReportPropertyChanging("State1DateTimeUtc");
                _State1DateTimeUtc = StructuralObject.SetValidValue(value, "State1DateTimeUtc");
                ReportPropertyChanged("State1DateTimeUtc");
                OnState1DateTimeUtcChanged();
            }
        }
        private Nullable<global::System.DateTime> _State1DateTimeUtc;
        partial void OnState1DateTimeUtcChanging(Nullable<global::System.DateTime> value);
        partial void OnState1DateTimeUtcChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> State2DateTimeUtc
        {
            get
            {
                return _State2DateTimeUtc;
            }
            set
            {
                OnState2DateTimeUtcChanging(value);
                ReportPropertyChanging("State2DateTimeUtc");
                _State2DateTimeUtc = StructuralObject.SetValidValue(value, "State2DateTimeUtc");
                ReportPropertyChanged("State2DateTimeUtc");
                OnState2DateTimeUtcChanged();
            }
        }
        private Nullable<global::System.DateTime> _State2DateTimeUtc;
        partial void OnState2DateTimeUtcChanging(Nullable<global::System.DateTime> value);
        partial void OnState2DateTimeUtcChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> State3DateTimeUtc
        {
            get
            {
                return _State3DateTimeUtc;
            }
            set
            {
                OnState3DateTimeUtcChanging(value);
                ReportPropertyChanging("State3DateTimeUtc");
                _State3DateTimeUtc = StructuralObject.SetValidValue(value, "State3DateTimeUtc");
                ReportPropertyChanged("State3DateTimeUtc");
                OnState3DateTimeUtcChanged();
            }
        }
        private Nullable<global::System.DateTime> _State3DateTimeUtc;
        partial void OnState3DateTimeUtcChanging(Nullable<global::System.DateTime> value);
        partial void OnState3DateTimeUtcChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> State4DateTimeUtc
        {
            get
            {
                return _State4DateTimeUtc;
            }
            set
            {
                OnState4DateTimeUtcChanging(value);
                ReportPropertyChanging("State4DateTimeUtc");
                _State4DateTimeUtc = StructuralObject.SetValidValue(value, "State4DateTimeUtc");
                ReportPropertyChanged("State4DateTimeUtc");
                OnState4DateTimeUtcChanged();
            }
        }
        private Nullable<global::System.DateTime> _State4DateTimeUtc;
        partial void OnState4DateTimeUtcChanging(Nullable<global::System.DateTime> value);
        partial void OnState4DateTimeUtcChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> State5DateTimeUtc
        {
            get
            {
                return _State5DateTimeUtc;
            }
            set
            {
                OnState5DateTimeUtcChanging(value);
                ReportPropertyChanging("State5DateTimeUtc");
                _State5DateTimeUtc = StructuralObject.SetValidValue(value, "State5DateTimeUtc");
                ReportPropertyChanged("State5DateTimeUtc");
                OnState5DateTimeUtcChanged();
            }
        }
        private Nullable<global::System.DateTime> _State5DateTimeUtc;
        partial void OnState5DateTimeUtcChanging(Nullable<global::System.DateTime> value);
        partial void OnState5DateTimeUtcChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> State6DateTimeUtc
        {
            get
            {
                return _State6DateTimeUtc;
            }
            set
            {
                OnState6DateTimeUtcChanging(value);
                ReportPropertyChanging("State6DateTimeUtc");
                _State6DateTimeUtc = StructuralObject.SetValidValue(value, "State6DateTimeUtc");
                ReportPropertyChanged("State6DateTimeUtc");
                OnState6DateTimeUtcChanged();
            }
        }
        private Nullable<global::System.DateTime> _State6DateTimeUtc;
        partial void OnState6DateTimeUtcChanging(Nullable<global::System.DateTime> value);
        partial void OnState6DateTimeUtcChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> State7DateTimeUtc
        {
            get
            {
                return _State7DateTimeUtc;
            }
            set
            {
                OnState7DateTimeUtcChanging(value);
                ReportPropertyChanging("State7DateTimeUtc");
                _State7DateTimeUtc = StructuralObject.SetValidValue(value, "State7DateTimeUtc");
                ReportPropertyChanged("State7DateTimeUtc");
                OnState7DateTimeUtcChanged();
            }
        }
        private Nullable<global::System.DateTime> _State7DateTimeUtc;
        partial void OnState7DateTimeUtcChanging(Nullable<global::System.DateTime> value);
        partial void OnState7DateTimeUtcChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> State8DateTimeUtc
        {
            get
            {
                return _State8DateTimeUtc;
            }
            set
            {
                OnState8DateTimeUtcChanging(value);
                ReportPropertyChanging("State8DateTimeUtc");
                _State8DateTimeUtc = StructuralObject.SetValidValue(value, "State8DateTimeUtc");
                ReportPropertyChanged("State8DateTimeUtc");
                OnState8DateTimeUtcChanged();
            }
        }
        private Nullable<global::System.DateTime> _State8DateTimeUtc;
        partial void OnState8DateTimeUtcChanging(Nullable<global::System.DateTime> value);
        partial void OnState8DateTimeUtcChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> State9DateTimeUtc
        {
            get
            {
                return _State9DateTimeUtc;
            }
            set
            {
                OnState9DateTimeUtcChanging(value);
                ReportPropertyChanging("State9DateTimeUtc");
                _State9DateTimeUtc = StructuralObject.SetValidValue(value, "State9DateTimeUtc");
                ReportPropertyChanged("State9DateTimeUtc");
                OnState9DateTimeUtcChanged();
            }
        }
        private Nullable<global::System.DateTime> _State9DateTimeUtc;
        partial void OnState9DateTimeUtcChanging(Nullable<global::System.DateTime> value);
        partial void OnState9DateTimeUtcChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> State10DateTimeUtc
        {
            get
            {
                return _State10DateTimeUtc;
            }
            set
            {
                OnState10DateTimeUtcChanging(value);
                ReportPropertyChanging("State10DateTimeUtc");
                _State10DateTimeUtc = StructuralObject.SetValidValue(value, "State10DateTimeUtc");
                ReportPropertyChanged("State10DateTimeUtc");
                OnState10DateTimeUtcChanged();
            }
        }
        private Nullable<global::System.DateTime> _State10DateTimeUtc;
        partial void OnState10DateTimeUtcChanging(Nullable<global::System.DateTime> value);
        partial void OnState10DateTimeUtcChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> State11DateTimeUtc
        {
            get
            {
                return _State11DateTimeUtc;
            }
            set
            {
                OnState11DateTimeUtcChanging(value);
                ReportPropertyChanging("State11DateTimeUtc");
                _State11DateTimeUtc = StructuralObject.SetValidValue(value, "State11DateTimeUtc");
                ReportPropertyChanged("State11DateTimeUtc");
                OnState11DateTimeUtcChanged();
            }
        }
        private Nullable<global::System.DateTime> _State11DateTimeUtc;
        partial void OnState11DateTimeUtcChanging(Nullable<global::System.DateTime> value);
        partial void OnState11DateTimeUtcChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> State12DateTimeUtc
        {
            get
            {
                return _State12DateTimeUtc;
            }
            set
            {
                OnState12DateTimeUtcChanging(value);
                ReportPropertyChanging("State12DateTimeUtc");
                _State12DateTimeUtc = StructuralObject.SetValidValue(value, "State12DateTimeUtc");
                ReportPropertyChanged("State12DateTimeUtc");
                OnState12DateTimeUtcChanged();
            }
        }
        private Nullable<global::System.DateTime> _State12DateTimeUtc;
        partial void OnState12DateTimeUtcChanging(Nullable<global::System.DateTime> value);
        partial void OnState12DateTimeUtcChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> State13DateTimeUtc
        {
            get
            {
                return _State13DateTimeUtc;
            }
            set
            {
                OnState13DateTimeUtcChanging(value);
                ReportPropertyChanging("State13DateTimeUtc");
                _State13DateTimeUtc = StructuralObject.SetValidValue(value, "State13DateTimeUtc");
                ReportPropertyChanged("State13DateTimeUtc");
                OnState13DateTimeUtcChanged();
            }
        }
        private Nullable<global::System.DateTime> _State13DateTimeUtc;
        partial void OnState13DateTimeUtcChanging(Nullable<global::System.DateTime> value);
        partial void OnState13DateTimeUtcChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> State14DateTimeUtc
        {
            get
            {
                return _State14DateTimeUtc;
            }
            set
            {
                OnState14DateTimeUtcChanging(value);
                ReportPropertyChanging("State14DateTimeUtc");
                _State14DateTimeUtc = StructuralObject.SetValidValue(value, "State14DateTimeUtc");
                ReportPropertyChanged("State14DateTimeUtc");
                OnState14DateTimeUtcChanged();
            }
        }
        private Nullable<global::System.DateTime> _State14DateTimeUtc;
        partial void OnState14DateTimeUtcChanging(Nullable<global::System.DateTime> value);
        partial void OnState14DateTimeUtcChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> State15DateTimeUtc
        {
            get
            {
                return _State15DateTimeUtc;
            }
            set
            {
                OnState15DateTimeUtcChanging(value);
                ReportPropertyChanging("State15DateTimeUtc");
                _State15DateTimeUtc = StructuralObject.SetValidValue(value, "State15DateTimeUtc");
                ReportPropertyChanged("State15DateTimeUtc");
                OnState15DateTimeUtcChanged();
            }
        }
        private Nullable<global::System.DateTime> _State15DateTimeUtc;
        partial void OnState15DateTimeUtcChanging(Nullable<global::System.DateTime> value);
        partial void OnState15DateTimeUtcChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> State16DateTimeUtc
        {
            get
            {
                return _State16DateTimeUtc;
            }
            set
            {
                OnState16DateTimeUtcChanging(value);
                ReportPropertyChanging("State16DateTimeUtc");
                _State16DateTimeUtc = StructuralObject.SetValidValue(value, "State16DateTimeUtc");
                ReportPropertyChanged("State16DateTimeUtc");
                OnState16DateTimeUtcChanged();
            }
        }
        private Nullable<global::System.DateTime> _State16DateTimeUtc;
        partial void OnState16DateTimeUtcChanging(Nullable<global::System.DateTime> value);
        partial void OnState16DateTimeUtcChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> State17DateTimeUtc
        {
            get
            {
                return _State17DateTimeUtc;
            }
            set
            {
                OnState17DateTimeUtcChanging(value);
                ReportPropertyChanging("State17DateTimeUtc");
                _State17DateTimeUtc = StructuralObject.SetValidValue(value, "State17DateTimeUtc");
                ReportPropertyChanged("State17DateTimeUtc");
                OnState17DateTimeUtcChanged();
            }
        }
        private Nullable<global::System.DateTime> _State17DateTimeUtc;
        partial void OnState17DateTimeUtcChanging(Nullable<global::System.DateTime> value);
        partial void OnState17DateTimeUtcChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateTimeUtc
        {
            get
            {
                return _DateTimeUtc;
            }
            set
            {
                OnDateTimeUtcChanging(value);
                ReportPropertyChanging("DateTimeUtc");
                _DateTimeUtc = StructuralObject.SetValidValue(value, "DateTimeUtc");
                ReportPropertyChanged("DateTimeUtc");
                OnDateTimeUtcChanged();
            }
        }
        private global::System.DateTime _DateTimeUtc;
        partial void OnDateTimeUtcChanging(global::System.DateTime value);
        partial void OnDateTimeUtcChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LogStoreModel", "ActivityEntryLogEntry", "LogEntry")]
        public EntityCollection<LogEntry> LogEntries
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<LogEntry>("LogStoreModel.ActivityEntryLogEntry", "LogEntry");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<LogEntry>("LogStoreModel.ActivityEntryLogEntry", "LogEntry", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LogStoreModel", Name="LogEntry")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LogEntry : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LogEntry object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        /// <param name="sourceTypeName">Initial value of the SourceTypeName property.</param>
        /// <param name="sourceMemberName">Initial value of the SourceMemberName property.</param>
        /// <param name="processId">Initial value of the ProcessId property.</param>
        /// <param name="appDomainId">Initial value of the AppDomainId property.</param>
        /// <param name="threadId">Initial value of the ThreadId property.</param>
        /// <param name="objectId">Initial value of the ObjectId property.</param>
        /// <param name="user">Initial value of the User property.</param>
        /// <param name="machine">Initial value of the Machine property.</param>
        /// <param name="dateTimeUtc">Initial value of the DateTimeUtc property.</param>
        /// <param name="cloudTenantId">Initial value of the CloudTenantId property.</param>
        /// <param name="content">Initial value of the Content property.</param>
        public static LogEntry CreateLogEntry(global::System.Guid id, global::System.String type, global::System.String sourceTypeName, global::System.String sourceMemberName, global::System.Int32 processId, global::System.Int32 appDomainId, global::System.Int32 threadId, global::System.Int32 objectId, global::System.String user, global::System.String machine, global::System.DateTime dateTimeUtc, global::System.String cloudTenantId, global::System.String content)
        {
            LogEntry logEntry = new LogEntry();
            logEntry.Id = id;
            logEntry.Type = type;
            logEntry.SourceTypeName = sourceTypeName;
            logEntry.SourceMemberName = sourceMemberName;
            logEntry.ProcessId = processId;
            logEntry.AppDomainId = appDomainId;
            logEntry.ThreadId = threadId;
            logEntry.ObjectId = objectId;
            logEntry.User = user;
            logEntry.Machine = machine;
            logEntry.DateTimeUtc = dateTimeUtc;
            logEntry.CloudTenantId = cloudTenantId;
            logEntry.Content = content;
            return logEntry;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, false, "Type");
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SourceTypeName
        {
            get
            {
                return _SourceTypeName;
            }
            set
            {
                OnSourceTypeNameChanging(value);
                ReportPropertyChanging("SourceTypeName");
                _SourceTypeName = StructuralObject.SetValidValue(value, false, "SourceTypeName");
                ReportPropertyChanged("SourceTypeName");
                OnSourceTypeNameChanged();
            }
        }
        private global::System.String _SourceTypeName;
        partial void OnSourceTypeNameChanging(global::System.String value);
        partial void OnSourceTypeNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SourceMemberName
        {
            get
            {
                return _SourceMemberName;
            }
            set
            {
                OnSourceMemberNameChanging(value);
                ReportPropertyChanging("SourceMemberName");
                _SourceMemberName = StructuralObject.SetValidValue(value, false, "SourceMemberName");
                ReportPropertyChanged("SourceMemberName");
                OnSourceMemberNameChanged();
            }
        }
        private global::System.String _SourceMemberName;
        partial void OnSourceMemberNameChanging(global::System.String value);
        partial void OnSourceMemberNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProcessId
        {
            get
            {
                return _ProcessId;
            }
            set
            {
                OnProcessIdChanging(value);
                ReportPropertyChanging("ProcessId");
                _ProcessId = StructuralObject.SetValidValue(value, "ProcessId");
                ReportPropertyChanged("ProcessId");
                OnProcessIdChanged();
            }
        }
        private global::System.Int32 _ProcessId;
        partial void OnProcessIdChanging(global::System.Int32 value);
        partial void OnProcessIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AppDomainId
        {
            get
            {
                return _AppDomainId;
            }
            set
            {
                OnAppDomainIdChanging(value);
                ReportPropertyChanging("AppDomainId");
                _AppDomainId = StructuralObject.SetValidValue(value, "AppDomainId");
                ReportPropertyChanged("AppDomainId");
                OnAppDomainIdChanged();
            }
        }
        private global::System.Int32 _AppDomainId;
        partial void OnAppDomainIdChanging(global::System.Int32 value);
        partial void OnAppDomainIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ThreadId
        {
            get
            {
                return _ThreadId;
            }
            set
            {
                OnThreadIdChanging(value);
                ReportPropertyChanging("ThreadId");
                _ThreadId = StructuralObject.SetValidValue(value, "ThreadId");
                ReportPropertyChanged("ThreadId");
                OnThreadIdChanged();
            }
        }
        private global::System.Int32 _ThreadId;
        partial void OnThreadIdChanging(global::System.Int32 value);
        partial void OnThreadIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ObjectId
        {
            get
            {
                return _ObjectId;
            }
            set
            {
                OnObjectIdChanging(value);
                ReportPropertyChanging("ObjectId");
                _ObjectId = StructuralObject.SetValidValue(value, "ObjectId");
                ReportPropertyChanged("ObjectId");
                OnObjectIdChanged();
            }
        }
        private global::System.Int32 _ObjectId;
        partial void OnObjectIdChanging(global::System.Int32 value);
        partial void OnObjectIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String User
        {
            get
            {
                return _User;
            }
            set
            {
                OnUserChanging(value);
                ReportPropertyChanging("User");
                _User = StructuralObject.SetValidValue(value, false, "User");
                ReportPropertyChanged("User");
                OnUserChanged();
            }
        }
        private global::System.String _User;
        partial void OnUserChanging(global::System.String value);
        partial void OnUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Machine
        {
            get
            {
                return _Machine;
            }
            set
            {
                OnMachineChanging(value);
                ReportPropertyChanging("Machine");
                _Machine = StructuralObject.SetValidValue(value, false, "Machine");
                ReportPropertyChanged("Machine");
                OnMachineChanged();
            }
        }
        private global::System.String _Machine;
        partial void OnMachineChanging(global::System.String value);
        partial void OnMachineChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateTimeUtc
        {
            get
            {
                return _DateTimeUtc;
            }
            set
            {
                OnDateTimeUtcChanging(value);
                ReportPropertyChanging("DateTimeUtc");
                _DateTimeUtc = StructuralObject.SetValidValue(value, "DateTimeUtc");
                ReportPropertyChanged("DateTimeUtc");
                OnDateTimeUtcChanged();
            }
        }
        private global::System.DateTime _DateTimeUtc;
        partial void OnDateTimeUtcChanging(global::System.DateTime value);
        partial void OnDateTimeUtcChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CloudTenantId
        {
            get
            {
                return _CloudTenantId;
            }
            set
            {
                OnCloudTenantIdChanging(value);
                ReportPropertyChanging("CloudTenantId");
                _CloudTenantId = StructuralObject.SetValidValue(value, false, "CloudTenantId");
                ReportPropertyChanged("CloudTenantId");
                OnCloudTenantIdChanged();
            }
        }
        private global::System.String _CloudTenantId;
        partial void OnCloudTenantIdChanging(global::System.String value);
        partial void OnCloudTenantIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> CloudRequestId
        {
            get
            {
                return _CloudRequestId;
            }
            set
            {
                OnCloudRequestIdChanging(value);
                ReportPropertyChanging("CloudRequestId");
                _CloudRequestId = StructuralObject.SetValidValue(value, "CloudRequestId");
                ReportPropertyChanged("CloudRequestId");
                OnCloudRequestIdChanged();
            }
        }
        private Nullable<global::System.Guid> _CloudRequestId;
        partial void OnCloudRequestIdChanging(Nullable<global::System.Guid> value);
        partial void OnCloudRequestIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Content
        {
            get
            {
                return _Content;
            }
            set
            {
                OnContentChanging(value);
                ReportPropertyChanging("Content");
                _Content = StructuralObject.SetValidValue(value, false, "Content");
                ReportPropertyChanged("Content");
                OnContentChanged();
            }
        }
        private global::System.String _Content;
        partial void OnContentChanging(global::System.String value);
        partial void OnContentChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LogStoreModel", "ActivityEntryLogEntry", "ActivityEntry")]
        public ActivityEntry ActivityEntry
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ActivityEntry>("LogStoreModel.ActivityEntryLogEntry", "ActivityEntry").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ActivityEntry>("LogStoreModel.ActivityEntryLogEntry", "ActivityEntry").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ActivityEntry> ActivityEntryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ActivityEntry>("LogStoreModel.ActivityEntryLogEntry", "ActivityEntry");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ActivityEntry>("LogStoreModel.ActivityEntryLogEntry", "ActivityEntry", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
