//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectorServiceMonitor.ViewModel {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConnectorServiceMonitor.ViewModel.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To change the {BriefProductName} server:.
        /// </summary>
        public static string CHANGE_SERVER {
            get {
                return ResourceManager.GetString("CHANGE_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change {BriefProductName} Server.
        /// </summary>
        public static string CHANGE_SERVER_TITLE {
            get {
                return ResourceManager.GetString("CHANGE_SERVER_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back office connectivity broken.
        /// </summary>
        public static string Connection_BackOfficeConnState_ConnectivityBroken {
            get {
                return ResourceManager.GetString("Connection_BackOfficeConnState_ConnectivityBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back office incompatible with Connector.
        /// </summary>
        public static string Connection_BackOfficeConnState_Incompatible {
            get {
                return ResourceManager.GetString("Connection_BackOfficeConnState_Incompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown back office connection error.
        /// </summary>
        public static string Connection_BackOfficeConnState_None {
            get {
                return ResourceManager.GetString("Connection_BackOfficeConnState_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal back office connection.
        /// </summary>
        public static string Connection_BackOfficeConnState_Normal {
            get {
                return ResourceManager.GetString("Connection_BackOfficeConnState_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud is currently unavailable.
        /// </summary>
        public static string Connection_TenantConnState_CloudUnavailable {
            get {
                return ResourceManager.GetString("Connection_TenantConnState_CloudUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud communication failed.
        /// </summary>
        public static string Connection_TenantConnState_CommunicationFailure {
            get {
                return ResourceManager.GetString("Connection_TenantConnState_CommunicationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gateway service is unavailable.
        /// </summary>
        public static string Connection_TenantConnState_GatewayServiceUnavailable {
            get {
                return ResourceManager.GetString("Connection_TenantConnState_GatewayServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connector incompatible with cloud.
        /// </summary>
        public static string Connection_TenantConnState_IncompatibleClient {
            get {
                return ResourceManager.GetString("Connection_TenantConnState_IncompatibleClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet connection is unavailable.
        /// </summary>
        public static string Connection_TenantConnState_InternetConnUnavailable {
            get {
                return ResourceManager.GetString("Connection_TenantConnState_InternetConnUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid connection information.
        /// </summary>
        public static string Connection_TenantConnState_InvalidConnectionInfo {
            get {
                return ResourceManager.GetString("Connection_TenantConnState_InvalidConnectionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local network is unavailable.
        /// </summary>
        public static string Connection_TenantConnState_LocalNetworkUnavailable {
            get {
                return ResourceManager.GetString("Connection_TenantConnState_LocalNetworkUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown cloud connection error.
        /// </summary>
        public static string Connection_TenantConnState_None {
            get {
                return ResourceManager.GetString("Connection_TenantConnState_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal cloud connection.
        /// </summary>
        public static string Connection_TenantConnState_Normal {
            get {
                return ResourceManager.GetString("Connection_TenantConnState_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconfiguring cloud connection.
        /// </summary>
        public static string Connection_TenantConnState_Reconfigure {
            get {
                return ResourceManager.GetString("Connection_TenantConnState_Reconfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant is currently disabled.
        /// </summary>
        public static string Connection_TenantConnState_TenantDisabled {
            get {
                return ResourceManager.GetString("Connection_TenantConnState_TenantDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud connection status.
        /// </summary>
        public static string Connections_Col1_ConectionStatus {
            get {
                return ResourceManager.GetString("Connections_Col1_ConectionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled connection modes.
        /// </summary>
        public static string Connections_Col1_IntegrationModes {
            get {
                return ResourceManager.GetString("Connections_Col1_IntegrationModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last communication attempt:.
        /// </summary>
        public static string Connections_Col1_LastCommunicationAttempt {
            get {
                return ResourceManager.GetString("Connections_Col1_LastCommunicationAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last successful communication:.
        /// </summary>
        public static string Connections_Col1_LastSuccessfulCommunication {
            get {
                return ResourceManager.GetString("Connections_Col1_LastSuccessfulCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next scheduled communication:.
        /// </summary>
        public static string Connections_Col1_NextScheduledCommunication {
            get {
                return ResourceManager.GetString("Connections_Col1_NextScheduledCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests in progress.
        /// </summary>
        public static string Connections_Col1_RequestsInProgress {
            get {
                return ResourceManager.GetString("Connections_Col1_RequestsInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests received.
        /// </summary>
        public static string Connections_Col1_RequestsRecieved {
            get {
                return ResourceManager.GetString("Connections_Col1_RequestsRecieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responses sent.
        /// </summary>
        public static string Connections_Col1_ResponsesSent {
            get {
                return ResourceManager.GetString("Connections_Col1_ResponsesSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive disabled.
        /// </summary>
        public static string Connections_Integration_GetDisabled {
            get {
                return ResourceManager.GetString("Connections_Integration_GetDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send disabled.
        /// </summary>
        public static string Connections_Integration_PutDisabled {
            get {
                return ResourceManager.GetString("Connections_Integration_PutDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection disabled.
        /// </summary>
        public static string Connections_IntegrationDisabled {
            get {
                return ResourceManager.GetString("Connections_IntegrationDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not processing.
        /// </summary>
        public static string Connections_IntegrationNotProcessing {
            get {
                return ResourceManager.GetString("Connections_IntegrationNotProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string Connections_IntegrationProcessing {
            get {
                return ResourceManager.GetString("Connections_IntegrationProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///        &lt;td width=&apos;{Column1Width}&apos; height=&apos;{RowHeight}&apos;&gt;
        ///          &lt;b&gt;{FieldName}&lt;/b&gt;
        ///        &lt;/td&gt;
        ///        &lt;td&gt;{ImageHtmlFragment}&amp;nbsp;{FieldValue}&lt;/td&gt;
        ///      &lt;/tr&gt;
        ///      {AdditionalHtml}.
        /// </summary>
        public static string General_2ColRow_Bold_HtmlFragment {
            get {
                return ResourceManager.GetString("General_2ColRow_Bold_HtmlFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///        &lt;td width=&apos;{Column1Width}&apos; height=&apos;{RowHeight}&apos;&gt;
        ///          &lt;b&gt;{FieldName}&lt;/b&gt;
        ///        &lt;/td&gt;
        ///        &lt;td&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;{ImageHtmlFragment}&amp;nbsp;{FieldValue}&lt;/td&gt;
        ///      &lt;/tr&gt;
        ///      {AdditionalHtml}.
        /// </summary>
        public static string General_2ColRow_Bold_HtmlFragment1_Col2Indent {
            get {
                return ResourceManager.GetString("General_2ColRow_Bold_HtmlFragment1_Col2Indent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///  &lt;td&gt;&amp;nbsp;&lt;/td&gt;
        ///  &lt;td&gt;&amp;nbsp;&lt;/td&gt;
        ///&lt;/tr&gt;
        ///      {AdditionalHtml}.
        /// </summary>
        public static string General_2ColRow_Empty_HtmlFragment {
            get {
                return ResourceManager.GetString("General_2ColRow_Empty_HtmlFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///        &lt;td width=&apos;{Column1Width}&apos; height=&apos;{RowHeight}&apos;&gt;
        ///          {FieldName}
        ///        &lt;/td&gt;
        ///        &lt;td&gt;{ImageHtmlFragment}&amp;nbsp;{FieldValue}&lt;/td&gt;
        ///      &lt;/tr&gt;
        ///      {AdditionalHtml}.
        /// </summary>
        public static string General_2ColRow_HtmlFragment {
            get {
                return ResourceManager.GetString("General_2ColRow_HtmlFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table border=&apos;0&apos; cellpadding=&apos;0&apos; cellspacing=&apos;0&apos; class=&apos;padded-table&apos;&gt;
        ///  {AdditionalHtml}
        ///&lt;/table&gt;
        ///{AdditionalTableHtml}.
        /// </summary>
        public static string General_2ColTable_HtmlFragment {
            get {
                return ResourceManager.GetString("General_2ColTable_HtmlFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;
        ///        &lt;td width=&apos;{Column1Width}&apos; height=&apos;{RowHeight}&apos;&gt;
        ///         &lt;b&gt; {FieldName}&lt;/b&gt;
        ///        &lt;/td&gt;
        ///	&lt;td width=&apos;{Column2Width}&apos; align=&apos;right&apos;&gt;
        ///	  {FieldValue2}
        ///	&lt;/td&gt;
        ///	
        ///        &lt;td&gt;{ImageHtmlFragment}&amp;nbsp;{FieldValue3}&lt;/td&gt;
        ///      &lt;/tr&gt;
        ///      {AdditionalHtml}.
        /// </summary>
        public static string General_3ColRow_Bold_HtmlFragment {
            get {
                return ResourceManager.GetString("General_3ColRow_Bold_HtmlFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table border=&apos;0&apos; cellpadding=&apos;0&apos; cellspacing=&apos;0&apos; class=&apos;padded-table&apos;&gt;
        ///  {AdditionalHtml}
        ///&lt;/table&gt;
        ///{AdditionalTableHtml}.
        /// </summary>
        public static string General_3ColTable_HtmlFragment {
            get {
                return ResourceManager.GetString("General_3ColTable_HtmlFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Connection.
        /// </summary>
        public static string General_AggregateCloudConnectionName {
            get {
                return ResourceManager.GetString("General_AggregateCloudConnectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&apos;csm://applyupdate&apos;&gt;Apply Update&lt;/a&gt;.
        /// </summary>
        public static string General_ApplyUpdateLink {
            get {
                return ResourceManager.GetString("General_ApplyUpdateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back office interface update required.
        /// </summary>
        public static string General_BackofficeUpdateRequired {
            get {
                return ResourceManager.GetString("General_BackofficeUpdateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to validate back office interface version.
        /// </summary>
        public static string General_BackofficeVersionUnknownIssue {
            get {
                return ResourceManager.GetString("General_BackofficeVersionUnknownIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall system status.
        /// </summary>
        public static string General_Col1_AggregateStatus {
            get {
                return ResourceManager.GetString("General_Col1_AggregateStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back office version.
        /// </summary>
        public static string General_Col1_BackofficeVersion {
            get {
                return ResourceManager.GetString("General_Col1_BackofficeVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site status.
        /// </summary>
        public static string General_Col1_CloudServiceStatus {
            get {
                return ResourceManager.GetString("General_Col1_CloudServiceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Connection.
        /// </summary>
        public static string General_Col1_ConnectionNoNumber {
            get {
                return ResourceManager.GetString("General_Col1_ConnectionNoNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Connection #{0}.
        /// </summary>
        public static string General_Col1_ConnectionNumber {
            get {
                return ResourceManager.GetString("General_Col1_ConnectionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connector monitor status.
        /// </summary>
        public static string General_Col1_ConnectorMonitorStatus {
            get {
                return ResourceManager.GetString("General_Col1_ConnectorMonitorStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connector status.
        /// </summary>
        public static string General_Col1_ConnectorStatus {
            get {
                return ResourceManager.GetString("General_Col1_ConnectorStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connector update.
        /// </summary>
        public static string General_Col1_ConnectorUpdate {
            get {
                return ResourceManager.GetString("General_Col1_ConnectorUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connector uptime.
        /// </summary>
        public static string General_Col1_ConnectorUptime {
            get {
                return ResourceManager.GetString("General_Col1_ConnectorUptime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connector version.
        /// </summary>
        public static string General_Col1_ConnectorVersion {
            get {
                return ResourceManager.GetString("General_Col1_ConnectorVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string General_Col1_Restart {
            get {
                return ResourceManager.GetString("General_Col1_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local system status.
        /// </summary>
        public static string General_Col1_SystemStatus {
            get {
                return ResourceManager.GetString("General_Col1_SystemStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string General_Connector_ConnectedState {
            get {
                return ResourceManager.GetString("General_Connector_ConnectedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connectivity error.
        /// </summary>
        public static string General_Connector_ConnectivityErrorState {
            get {
                return ResourceManager.GetString("General_Connector_ConnectivityErrorState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        public static string General_Connector_NoneState {
            get {
                return ResourceManager.GetString("General_Connector_NoneState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service not ready.
        /// </summary>
        public static string General_Connector_ServiceNotReadyState {
            get {
                return ResourceManager.GetString("General_Connector_ServiceNotReadyState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service not registered.
        /// </summary>
        public static string General_Connector_ServiceNotRegisteredState {
            get {
                return ResourceManager.GetString("General_Connector_ServiceNotRegisteredState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service not running.
        /// </summary>
        public static string General_Connector_ServiceNotRunningState {
            get {
                return ResourceManager.GetString("General_Connector_ServiceNotRunningState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string General_ConnectorMonitor_ReadyState {
            get {
                return ResourceManager.GetString("General_ConnectorMonitor_ReadyState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing.
        /// </summary>
        public static string General_ConnectorMonitor_RecyclingState {
            get {
                return ResourceManager.GetString("General_ConnectorMonitor_RecyclingState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servicing request.
        /// </summary>
        public static string General_ConnectorMonitor_ServicingRequestState {
            get {
                return ResourceManager.GetString("General_ConnectorMonitor_ServicingRequestState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;style&gt;
        ///      &lt;!--
        ///body { font-family: {FontFamilyName};  font-size:{FontSizeInPoints}pt; }
        ///td { font-family: {FontFamilyName};  font-size:{FontSizeInPoints}pt; }
        ///table.padded-table td {padding:0px 5px 0px 5px;}
        ///--&gt;
        ///    &lt;/style&gt;
        ///  &lt;/head&gt;
        ///  &lt;body scroll=&apos;auto&apos; bgcolor=&quot;#{WindowBackgroundColor}&quot;&gt;
        ///    &lt;table border=&apos;0&apos; cellpadding=&apos;0&apos; cellspacing=&apos;0&apos; class=&apos;padded-table&apos;&gt;
        ///  {AdditionalHtml}
        ///&lt;/table&gt;
        ///  &lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        public static string General_HtmlDocument {
            get {
                return ResourceManager.GetString("General_HtmlDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;style&gt;
        ///      &lt;!--
        ///body { font-family: {FontFamilyName};  font-size:{FontSizeInPoints}pt; }
        ///td { font-family: {FontFamilyName};  font-size:{FontSizeInPoints}pt; }
        ///table.padded-table td {padding:0px 5px 0px 5px;}
        ///--&gt;
        ///    &lt;/style&gt;
        ///  &lt;/head&gt;
        ///  &lt;body scroll=&apos;auto&apos; bgcolor=&quot;#{WindowBackgroundColor}&quot;&gt;
        ///    {AdditionalTableHtml}
        ///  &lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        public static string General_HtmlDocumentMultiTable {
            get {
                return ResourceManager.GetString("General_HtmlDocumentMultiTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img border=&apos;0&apos; align=&apos;absmiddle&apos; src=&apos;file:///{BitmapSource}&apos;/&gt;.
        /// </summary>
        public static string General_ImageHtmlFragment {
            get {
                return ResourceManager.GetString("General_ImageHtmlFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img border=&apos;0&apos; align=&apos;absmiddle&apos; src=&apos;file:///{BitmapSource}&apos; alt=&apos;{AltText}&apos;/&gt;.
        /// </summary>
        public static string General_ImageWithAltHtmlFragment {
            get {
                return ResourceManager.GetString("General_ImageWithAltHtmlFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blackout (scheduled until {0}).
        /// </summary>
        public static string General_InternetConnectivityStatus_BlackoutMessageFormat {
            get {
                return ResourceManager.GetString("General_InternetConnectivityStatus_BlackoutMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud unavailable.
        /// </summary>
        public static string General_InternetConnectivityStatus_CloudUnavailableMessage {
            get {
                return ResourceManager.GetString("General_InternetConnectivityStatus_CloudUnavailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication failure.
        /// </summary>
        public static string General_InternetConnectivityStatus_CommunicationFailure {
            get {
                return ResourceManager.GetString("General_InternetConnectivityStatus_CommunicationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gateway service unavailable.
        /// </summary>
        public static string General_InternetConnectivityStatus_GatewayServiceUnavailable {
            get {
                return ResourceManager.GetString("General_InternetConnectivityStatus_GatewayServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet connection unavailable.
        /// </summary>
        public static string General_InternetConnectivityStatus_InternetConnectionUnavailableMessage {
            get {
                return ResourceManager.GetString("General_InternetConnectivityStatus_InternetConnectionUnavailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local network unavailable.
        /// </summary>
        public static string General_InternetConnectivityStatus_LocalNetworkUnavailableMessage {
            get {
                return ResourceManager.GetString("General_InternetConnectivityStatus_LocalNetworkUnavailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string General_InternetConnectivityStatus_UnknownMessage {
            get {
                return ResourceManager.GetString("General_InternetConnectivityStatus_UnknownMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up and running.
        /// </summary>
        public static string General_InternetConnectivityStatus_UpAndRunningMessage {
            get {
                return ResourceManager.GetString("General_InternetConnectivityStatus_UpAndRunningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can apply this update from the computer the connector is running on via the monitor application..
        /// </summary>
        public static string General_UpdateAvaibleOnConnectorMachine {
            get {
                return ResourceManager.GetString("General_UpdateAvaibleOnConnectorMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;Description:&lt;/li&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp; {0}.
        /// </summary>
        public static string General_UpdateDescription {
            get {
                return ResourceManager.GetString("General_UpdateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version ({0}) is now available (published on {1}).
        /// </summary>
        public static string General_UpdateIsAvailableMessageFormat {
            get {
                return ResourceManager.GetString("General_UpdateIsAvailableMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update to the connector is available..
        /// </summary>
        public static string General_UpdateIsAvailableMessageFormatNoVersion {
            get {
                return ResourceManager.GetString("General_UpdateIsAvailableMessageFormatNoVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version ({0}) is required (published on {1}).
        /// </summary>
        public static string General_UpdateIsRequiredMessageFormat {
            get {
                return ResourceManager.GetString("General_UpdateIsRequiredMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update to the connector is required..
        /// </summary>
        public static string General_UpdateIsRequiredMessageFormatNoVersion {
            get {
                return ResourceManager.GetString("General_UpdateIsRequiredMessageFormatNoVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;Update link:&lt;/li&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp; &lt;a href=&quot;{0}&quot; target=&quot;_blank&quot;&gt;Click here for update&lt;/a&gt;.
        /// </summary>
        public static string General_UpdateLink {
            get {
                return ResourceManager.GetString("General_UpdateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is the current version.
        /// </summary>
        public static string General_VersionIsCurrentMessageFormat {
            get {
                return ResourceManager.GetString("General_VersionIsCurrentMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;{0} is the current version&lt;/li&gt;.
        /// </summary>
        public static string General_VersionIsCurrentMessageFormatAsLineItem {
            get {
                return ResourceManager.GetString("General_VersionIsCurrentMessageFormatAsLineItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;{0} is the update identifier&lt;/li&gt;.
        /// </summary>
        public static string General_VersionIsUpdateMessageFormatAsLineItem {
            get {
                return ResourceManager.GetString("General_VersionIsUpdateMessageFormatAsLineItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;style&gt;
        ///      &lt;!--
        ///body { font-family: {FontFamilyName};  font-size:{FontSizeInPoints}pt; }
        ///td { font-family: {FontFamilyName};  font-size:{FontSizeInPoints}pt}
        ///--&gt;
        ///    &lt;/style&gt;
        ///  &lt;/head&gt;
        ///  &lt;body scroll=&apos;auto&apos; bgcolor=&quot;#{WindowBackgroundColor}&quot;&gt;
        ///    &lt;table style=&quot;width: 100%; height: 100%&quot; border=&apos;0&apos; cellpadding=&apos;0&apos; cellspacing=&apos;0&apos;&gt;
        ///      &lt;tr&gt;
        ///        &lt;td align=&apos;center&apos;&apos;&gt;{Message}&lt;/td&gt;
        ///      &lt;/tr&gt;
        ///    &lt;/table&gt;
        ///  &lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        public static string General_WelcomeHtmlDocument {
            get {
                return ResourceManager.GetString("General_WelcomeHtmlDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tool monitors the status of your {Common.BriefProductName} service.&lt;p/&gt;&lt;a href=&apos;csm://changesettings&apos;&gt;Change settings&lt;/a&gt; to configure the server to monitor..
        /// </summary>
        public static string General_WelcomeHtmlFragment {
            get {
                return ResourceManager.GetString("General_WelcomeHtmlFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://help.connector.na.sage.com/en-us/web/win/index.htm#cshid=4.
        /// </summary>
        public static string Help_Link {
            get {
                return ResourceManager.GetString("Help_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default_CSH.htm#10024.
        /// </summary>
        public static string HelpPathFragment_EnterIPForm {
            get {
                return ResourceManager.GetString("HelpPathFragment_EnterIPForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default_CSH.htm#10029.
        /// </summary>
        public static string HelpPathFragment_MainForm {
            get {
                return ResourceManager.GetString("HelpPathFragment_MainForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default_CSH.htm#10025.
        /// </summary>
        public static string HelpPathFragment_NetworkBrowserForm {
            get {
                return ResourceManager.GetString("HelpPathFragment_NetworkBrowserForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default_CSH.htm#10027.
        /// </summary>
        public static string HelpPathFragment_ServerSelectionForm_Change {
            get {
                return ResourceManager.GetString("HelpPathFragment_ServerSelectionForm_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default_CSH.htm#10026.
        /// </summary>
        public static string HelpPathFragment_ServerSelectionForm_Initialize {
            get {
                return ResourceManager.GetString("HelpPathFragment_ServerSelectionForm_Initialize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default_CSH.htm#10028.
        /// </summary>
        public static string HelpPathFragment_SpecifyServer_WhatIsServer {
            get {
                return ResourceManager.GetString("HelpPathFragment_SpecifyServer_WhatIsServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a {BriefProductName} server..
        /// </summary>
        public static string MACHINE_DOES_NOT_HAVE_SERVER_FORMAT {
            get {
                return ResourceManager.GetString("MACHINE_DOES_NOT_HAVE_SERVER_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not configured to be a {BriefProductName} server..
        /// </summary>
        public static string MACHINE_IS_NOT_A_SERVER_FORMAT {
            get {
                return ResourceManager.GetString("MACHINE_IS_NOT_A_SERVER_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not responding to connection requests..
        /// </summary>
        public static string MACHINE_NOT_RESPONDING {
            get {
                return ResourceManager.GetString("MACHINE_NOT_RESPONDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have a valid network connection..
        /// </summary>
        public static string NETWORK_CONNECTION_NOT_FOUND {
            get {
                return ResourceManager.GetString("NETWORK_CONNECTION_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud and back office connection issues were found.
        /// </summary>
        public static string NotifyIcon_CloudAndPremiseConnectionProblemsTooltip {
            get {
                return ResourceManager.GetString("NotifyIcon_CloudAndPremiseConnectionProblemsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud connection issues were found.
        /// </summary>
        public static string NotifyIcon_CloudConnectionProblemsTooltip {
            get {
                return ResourceManager.GetString("NotifyIcon_CloudConnectionProblemsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a connectivity error with the {TerseConnectorName} service.
        /// </summary>
        public static string NotifyIcon_ConnectivityErrorTooltip {
            get {
                return ResourceManager.GetString("NotifyIcon_ConnectivityErrorTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {TerseConnectorName} service is running normally.
        /// </summary>
        public static string NotifyIcon_NormalTooltip {
            get {
                return ResourceManager.GetString("NotifyIcon_NormalTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {TerseConnectorName} service is not configured.
        /// </summary>
        public static string NotifyIcon_NotConfiguredTooltip {
            get {
                return ResourceManager.GetString("NotifyIcon_NotConfiguredTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {TerseConnectorName} system is offline.
        /// </summary>
        public static string NotifyIcon_OfflineTooltip {
            get {
                return ResourceManager.GetString("NotifyIcon_OfflineTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back office connection issues were found.
        /// </summary>
        public static string NotifyIcon_PremiseConnectionProblemsTooltip {
            get {
                return ResourceManager.GetString("NotifyIcon_PremiseConnectionProblemsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {TerseConnectorName} service is busy.
        /// </summary>
        public static string NotifyIcon_ServiceBusyTooltip {
            get {
                return ResourceManager.GetString("NotifyIcon_ServiceBusyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {TerseConnectorName} service is not yet ready.
        /// </summary>
        public static string NotifyIcon_ServiceNotReadyTooltip {
            get {
                return ResourceManager.GetString("NotifyIcon_ServiceNotReadyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {TerseConnectorName} service is not configured.
        /// </summary>
        public static string NotifyIcon_ServiceNotRegisteredTooltip {
            get {
                return ResourceManager.GetString("NotifyIcon_ServiceNotRegisteredTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {TerseConnectorName} service is not running.
        /// </summary>
        public static string NotifyIcon_ServiceNotRunningTooltip {
            get {
                return ResourceManager.GetString("NotifyIcon_ServiceNotRunningTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {TerseConnectorName} update is available..
        /// </summary>
        public static string NotifyIcon_UpdateAvailableTooltip {
            get {
                return ResourceManager.GetString("NotifyIcon_UpdateAvailableTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {TerseConnectorName} update is required..
        /// </summary>
        public static string NotifyIcon_UpdateRequiredTooltip {
            get {
                return ResourceManager.GetString("NotifyIcon_UpdateRequiredTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed on.
        /// </summary>
        public static string Requests_ColHeader_CompletedOn {
            get {
                return ResourceManager.GetString("Requests_ColHeader_CompletedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed time.
        /// </summary>
        public static string Requests_ColHeader_ElapsedTime {
            get {
                return ResourceManager.GetString("Requests_ColHeader_ElapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name.
        /// </summary>
        public static string Requests_ColHeader_ProjectName {
            get {
                return ResourceManager.GetString("Requests_ColHeader_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested by.
        /// </summary>
        public static string Requests_ColHeader_RequestedBy {
            get {
                return ResourceManager.GetString("Requests_ColHeader_RequestedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Requests_ColHeader_RequestSummary {
            get {
                return ResourceManager.GetString("Requests_ColHeader_RequestSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started on.
        /// </summary>
        public static string Requests_ColHeader_StartedOn {
            get {
                return ResourceManager.GetString("Requests_ColHeader_StartedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Requests_ColHeader_Type {
            get {
                return ResourceManager.GetString("Requests_ColHeader_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Request Queued).
        /// </summary>
        public static string RequestsPageHtmlRenderer_DisplayValueForRequestType_DomainMediation {
            get {
                return ResourceManager.GetString("RequestsPageHtmlRenderer_DisplayValueForRequestType_DomainMediation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {BriefProductName} server is {0}..
        /// </summary>
        public static string SERVER {
            get {
                return ResourceManager.GetString("SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify Server Error.
        /// </summary>
        public static string SERVER_ERROR {
            get {
                return ResourceManager.GetString("SERVER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Changed.
        /// </summary>
        public static string SettingsUserControl__saveButton_Click_Server_Changed {
            get {
                return ResourceManager.GetString("SettingsUserControl__saveButton_Click_Server_Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to server successfully.
        /// </summary>
        public static string SettingsUserControl__saveServerChange_Connected_to_server_sucessfully {
            get {
                return ResourceManager.GetString("SettingsUserControl__saveServerChange_Connected_to_server_sucessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Computers on your network.
        /// </summary>
        public static string SettingsUserControl_DefaultforServerSelection_List_of_Computers_on_your_network {
            get {
                return ResourceManager.GetString("SettingsUserControl_DefaultforServerSelection_List_of_Computers_on_your_network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another Computer.
        /// </summary>
        public static string SettingsUserControl_InitilizeLabels_Another_Computer {
            get {
                return ResourceManager.GetString("SettingsUserControl_InitilizeLabels_Another_Computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter IP Address or Server Name.
        /// </summary>
        public static string SettingsUserControl_InitilizeLabels_Enter_IP_Address_or_Server_Name {
            get {
                return ResourceManager.GetString("SettingsUserControl_InitilizeLabels_Enter_IP_Address_or_Server_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 minutes.
        /// </summary>
        public static string SettingsUserControl_InitilizeLabels_Every_10_minutes {
            get {
                return ResourceManager.GetString("SettingsUserControl_InitilizeLabels_Every_10_minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 seconds.
        /// </summary>
        public static string SettingsUserControl_InitilizeLabels_Every_10_seconds {
            get {
                return ResourceManager.GetString("SettingsUserControl_InitilizeLabels_Every_10_seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 minutes.
        /// </summary>
        public static string SettingsUserControl_InitilizeLabels_Every_2_minutes {
            get {
                return ResourceManager.GetString("SettingsUserControl_InitilizeLabels_Every_2_minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 seconds.
        /// </summary>
        public static string SettingsUserControl_InitilizeLabels_Every_30_seconds {
            get {
                return ResourceManager.GetString("SettingsUserControl_InitilizeLabels_Every_30_seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 minutes.
        /// </summary>
        public static string SettingsUserControl_InitilizeLabels_Every_5_minutes {
            get {
                return ResourceManager.GetString("SettingsUserControl_InitilizeLabels_Every_5_minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 seconds.
        /// </summary>
        public static string SettingsUserControl_InitilizeLabels_Every_5_seconds {
            get {
                return ResourceManager.GetString("SettingsUserControl_InitilizeLabels_Every_5_seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60 seconds.
        /// </summary>
        public static string SettingsUserControl_InitilizeLabels_Every_60_seconds {
            get {
                return ResourceManager.GetString("SettingsUserControl_InitilizeLabels_Every_60_seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string SettingsUserControl_InitilizeLabels_Never {
            get {
                return ResourceManager.GetString("SettingsUserControl_InitilizeLabels_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string SettingsUserControl_InitilizeLabels_or {
            get {
                return ResourceManager.GetString("SettingsUserControl_InitilizeLabels_or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Number.
        /// </summary>
        public static string SettingsUserControl_InitilizeLabels_Port_Number {
            get {
                return ResourceManager.GetString("SettingsUserControl_InitilizeLabels_Port_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sage Connector Server:.
        /// </summary>
        public static string SettingsUserControl_InitilizeLabels_Sage_Connector_Server {
            get {
                return ResourceManager.GetString("SettingsUserControl_InitilizeLabels_Sage_Connector_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SettingsUserControl_InitilizeLabels_Save {
            get {
                return ResourceManager.GetString("SettingsUserControl_InitilizeLabels_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Computer.
        /// </summary>
        public static string SettingsUserControl_InitilizeLabels_Select_a_Computer {
            get {
                return ResourceManager.GetString("SettingsUserControl_InitilizeLabels_Select_a_Computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Computer.
        /// </summary>
        public static string SettingsUserControl_InitilizeLabels_This_Computer {
            get {
                return ResourceManager.GetString("SettingsUserControl_InitilizeLabels_This_Computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server List.
        /// </summary>
        public static string SettingsUserControl_LoadServerList_Caption {
            get {
                return ResourceManager.GetString("SettingsUserControl_LoadServerList_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load ServerList.Contact your Administrator.
        /// </summary>
        public static string SettingsUserControl_LoadServerList_Error {
            get {
                return ResourceManager.GetString("SettingsUserControl_LoadServerList_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To specify this computer:.
        /// </summary>
        public static string SPECIFY_SERVER {
            get {
                return ResourceManager.GetString("SPECIFY_SERVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error refreshing data.
        /// </summary>
        public static string StatusStrip_ErrorMessage {
            get {
                return ResourceManager.GetString("StatusStrip_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last refresh: {0}.
        /// </summary>
        public static string StatusStrip_LastRefreshMessageFormat {
            get {
                return ResourceManager.GetString("StatusStrip_LastRefreshMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing data....
        /// </summary>
        public static string StatusStrip_RefreshingMessage {
            get {
                return ResourceManager.GetString("StatusStrip_RefreshingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud and back office connection issues were found.
        /// </summary>
        public static string SysTrayBalloon_CloudAndPremiseConnectionProblemsMessage {
            get {
                return ResourceManager.GetString("SysTrayBalloon_CloudAndPremiseConnectionProblemsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud connection issues were found.
        /// </summary>
        public static string SysTrayBalloon_CloudConnectionProblemsMessage {
            get {
                return ResourceManager.GetString("SysTrayBalloon_CloudConnectionProblemsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a connectivity error with the {BriefProductName} service.
        /// </summary>
        public static string SysTrayBalloon_ConnectivityErrorMessage {
            get {
                return ResourceManager.GetString("SysTrayBalloon_ConnectivityErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {BriefProductName} service is running normally.
        /// </summary>
        public static string SysTrayBalloon_NormalMessage {
            get {
                return ResourceManager.GetString("SysTrayBalloon_NormalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {BriefProductName} service is not configured.
        /// </summary>
        public static string SysTrayBalloon_NotConfiguredMessage {
            get {
                return ResourceManager.GetString("SysTrayBalloon_NotConfiguredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {BriefProductName} system is offline.
        /// </summary>
        public static string SysTrayBalloon_OfflineMessage {
            get {
                return ResourceManager.GetString("SysTrayBalloon_OfflineMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back office connection issues were found.
        /// </summary>
        public static string SysTrayBalloon_PremiseConnectionProblemsMessage {
            get {
                return ResourceManager.GetString("SysTrayBalloon_PremiseConnectionProblemsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {BriefProductName} service is not yet ready.
        /// </summary>
        public static string SysTrayBalloon_ServiceNotReadyMessage {
            get {
                return ResourceManager.GetString("SysTrayBalloon_ServiceNotReadyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {BriefProductName} service is not configured.
        /// </summary>
        public static string SysTrayBalloon_ServiceNotRegisteredMessage {
            get {
                return ResourceManager.GetString("SysTrayBalloon_ServiceNotRegisteredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {BriefProductName} service is not running.
        /// </summary>
        public static string SysTrayBalloon_ServiceNotRunningMessage {
            get {
                return ResourceManager.GetString("SysTrayBalloon_ServiceNotRunningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {BriefProductName} Status.
        /// </summary>
        public static string SysTrayBalloon_Title {
            get {
                return ResourceManager.GetString("SysTrayBalloon_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {BriefProductName} update is available. Click here for more information..
        /// </summary>
        public static string SysTrayBalloon_UpdateAvailableMessage {
            get {
                return ResourceManager.GetString("SysTrayBalloon_UpdateAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {BriefProductName} update is required. Click here for more information..
        /// </summary>
        public static string SysTrayBalloon_UpdateRequiredMessage {
            get {
                return ResourceManager.GetString("SysTrayBalloon_UpdateRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connector.
        /// </summary>
        public static string Term_TerseConnectorName {
            get {
                return ResourceManager.GetString("Term_TerseConnectorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find {0}..
        /// </summary>
        public static string UNABLE_TO_FIND_SERVER_FORMAT {
            get {
                return ResourceManager.GetString("UNABLE_TO_FIND_SERVER_FORMAT", resourceCulture);
            }
        }
    }
}
