//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SageConnect.ViewModels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CustomerFacingMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomerFacingMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SageConnect.ViewModels.CustomerFacingMessages", typeof(CustomerFacingMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting/ERP Information.
        /// </summary>
        public static string AdminCredentialsCaption {
            get {
                return ResourceManager.GetString("AdminCredentialsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting/ERP System:.
        /// </summary>
        public static string BackOfficeCaption {
            get {
                return ResourceManager.GetString("BackOfficeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCaption_Cancel {
            get {
                return ResourceManager.GetString("ButtonCaption_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ButtonCaption_Ok {
            get {
                return ResourceManager.GetString("ButtonCaption_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string ButtonCaption_Register {
            get {
                return ResourceManager.GetString("ButtonCaption_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ButtonCaption_Save {
            get {
                return ResourceManager.GetString("ButtonCaption_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string ButtonCaption_Submit {
            get {
                return ResourceManager.GetString("ButtonCaption_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        public static string ButtonCaption_Validate {
            get {
                return ResourceManager.GetString("ButtonCaption_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Connector Connections.
        /// </summary>
        public static string Captiion_ConnectorConnections {
            get {
                return ResourceManager.GetString("Captiion_ConnectorConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ConfirmationDialog_Cancel {
            get {
                return ResourceManager.GetString("ConfirmationDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Settings.
        /// </summary>
        public static string ConfirmationDialog_ClearsettingsButton {
            get {
                return ResourceManager.GetString("ConfirmationDialog_ClearsettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Settings?.
        /// </summary>
        public static string ConfirmationDialog_ClearSettingsCaption {
            get {
                return ResourceManager.GetString("ConfirmationDialog_ClearSettingsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Information.
        /// </summary>
        public static string ConfirmationDialog_ClearSettingsHelp_Header {
            get {
                return ResourceManager.GetString("ConfirmationDialog_ClearSettingsHelp_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all connection and default transaction settings for this connection? 
        ///Settings will be cleared, but previously synchronized data will not be cleared from the Sage Data Cloud..
        /// </summary>
        public static string ConfirmationDialog_ClearSettingsMessage {
            get {
                return ResourceManager.GetString("ConfirmationDialog_ClearSettingsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections.
        /// </summary>
        public static string Connection_Connections {
            get {
                return ResourceManager.GetString("Connection_Connections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sage Data Cloud Connector.
        /// </summary>
        public static string Connection_FormCaption {
            get {
                return ResourceManager.GetString("Connection_FormCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting/ERP.
        /// </summary>
        public static string Connection_GridAccounting {
            get {
                return ResourceManager.GetString("Connection_GridAccounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud.
        /// </summary>
        public static string Connection_Gridcloud {
            get {
                return ResourceManager.GetString("Connection_Gridcloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Site.
        /// </summary>
        public static string Connection_Gridcustomersite {
            get {
                return ResourceManager.GetString("Connection_Gridcustomersite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting/ERP Connected.
        /// </summary>
        public static string Connection_ImageAccountingconnected {
            get {
                return ResourceManager.GetString("Connection_ImageAccountingconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting/ERP Not Set Up.
        /// </summary>
        public static string Connection_ImageAccountingnotsetup {
            get {
                return ResourceManager.GetString("Connection_ImageAccountingnotsetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Connected.
        /// </summary>
        public static string Connection_ImageCloudConnected {
            get {
                return ResourceManager.GetString("Connection_ImageCloudConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Not Set Up.
        /// </summary>
        public static string Connection_ImageCloudnotsetup {
            get {
                return ResourceManager.GetString("Connection_ImageCloudnotsetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string Connection_ImageConnected {
            get {
                return ResourceManager.GetString("Connection_ImageConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Error.
        /// </summary>
        public static string Connection_ImageConnectionerror {
            get {
                return ResourceManager.GetString("Connection_ImageConnectionerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Not Set Up.
        /// </summary>
        public static string Connection_Imageconnectionnotsetup {
            get {
                return ResourceManager.GetString("Connection_Imageconnectionnotsetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This list displays all connections associated with the Sage ID you used to sign in. Click a connection to set it up or to modify existing connection settings..
        /// </summary>
        public static string Connection_Message {
            get {
                return ResourceManager.GetString("Connection_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting/ERP Information.
        /// </summary>
        public static string ConnectionCredentialsCaption {
            get {
                return ResourceManager.GetString("ConnectionCredentialsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Details.
        /// </summary>
        public static string ConnectionDetails_Header {
            get {
                return ResourceManager.GetString("ConnectionDetails_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorCaption {
            get {
                return ResourceManager.GetString("ErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A technical problem occurred and the connection could not be created. .
        /// </summary>
        public static string ErrorMessage_CloudRegistratoinFailed {
            get {
                return ResourceManager.GetString("ErrorMessage_CloudRegistratoinFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Registration Failed.
        /// </summary>
        public static string ErrorMessage_CloudRegistratoinFailed_Caption {
            get {
                return ResourceManager.GetString("ErrorMessage_CloudRegistratoinFailed_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected company is already connected to a customer site {site/us}. You cannot connect a company to multiple customer sites..
        /// </summary>
        public static string ErrorMessage_CompanyRegisteredtodifferentTenant {
            get {
                return ResourceManager.GetString("ErrorMessage_CompanyRegisteredtodifferentTenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem occurred and your changes could not be saved. Error message:.
        /// </summary>
        public static string ErrorMessage_Connectionsavefailed {
            get {
                return ResourceManager.GetString("ErrorMessage_Connectionsavefailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot change the company that is selected for an existing connection..
        /// </summary>
        public static string ErrorMessage_DifferenentCompanySelectedonEdit {
            get {
                return ResourceManager.GetString("ErrorMessage_DifferenentCompanySelectedonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Configuration Error.
        /// </summary>
        public static string ErrorMessage_ErrorwhenlistingFeatureConfguration {
            get {
                return ResourceManager.GetString("ErrorMessage_ErrorwhenlistingFeatureConfguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Feature Configuration Details returned from BackOffice.
        /// </summary>
        public static string ErrorMessage_FeatureConfigurationNull {
            get {
                return ResourceManager.GetString("ErrorMessage_FeatureConfigurationNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some default transaction settings are missing required information, or contain information that could not be validated in your accounting or ERP system. Please review your settings and try again.
        /// </summary>
        public static string ErrorMessage_FeatureConfigValuesMissing {
            get {
                return ResourceManager.GetString("ErrorMessage_FeatureConfigValuesMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required values Missing.
        /// </summary>
        public static string ErrorMessage_FeatureConfivalueMisssing_Caption {
            get {
                return ResourceManager.GetString("ErrorMessage_FeatureConfivalueMisssing_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Information.
        /// </summary>
        public static string ErrorMessage_HyperLinkText {
            get {
                return ResourceManager.GetString("ErrorMessage_HyperLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization Error.
        /// </summary>
        public static string ErrorMessage_NoTenantCaption {
            get {
                return ResourceManager.GetString("ErrorMessage_NoTenantCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sage ID you entered is not authorized to configure Sage Data Cloud Connector. Sign in with an authorized Sage ID or contact your administrator for assistance..
        /// </summary>
        public static string ErrorMessage_NoTenantExists {
            get {
                return ResourceManager.GetString("ErrorMessage_NoTenantExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Settings.
        /// </summary>
        public static string Header_CustomerSettings {
            get {
                return ResourceManager.GetString("Header_CustomerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string InfoCaption {
            get {
                return ResourceManager.GetString("InfoCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Settings Saved.
        /// </summary>
        public static string InfoCaption_ConnectionSaved {
            get {
                return ResourceManager.GetString("InfoCaption_ConnectionSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Sage Mobile Sales.
        /// </summary>
        public static string InfoCaption_OpenConnectionMonitor {
            get {
                return ResourceManager.GetString("InfoCaption_OpenConnectionMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Modify Existing Connection.
        /// </summary>
        public static string InfoCaption_TenantConnectionExists {
            get {
                return ResourceManager.GetString("InfoCaption_TenantConnectionExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your connection settings have been saved and data is now being synchronized between your accounting or ERP system and Sage Data Cloud.
        ///
        ///Initial synchronization may take up to a few hours to complete,depending on the amount of data and your connection speed.
        ///
        ///You can safely close the configuration screen and begin using your Sage web and mobile applicatiions .Sage Data Cloud will continue to synchronize data in the background..
        /// </summary>
        public static string InfoMessage_ConnectionSaved {
            get {
                return ResourceManager.GetString("InfoMessage_ConnectionSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected customer site is connected to an accounting or ERP system on another computer. If you want to set up a new connection for this customer site, you must clear settings for the existing connection first..
        /// </summary>
        public static string InfoMessage_TenantConnectionExists {
            get {
                return ResourceManager.GetString("InfoMessage_TenantConnectionExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend.
        /// </summary>
        public static string Legend_Header {
            get {
                return ResourceManager.GetString("Legend_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading connection details..
        /// </summary>
        public static string Progressbar_LoadingConnection {
            get {
                return ResourceManager.GetString("Progressbar_LoadingConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh transaction settings....
        /// </summary>
        public static string Progressbar_Refreshtransaction {
            get {
                return ResourceManager.GetString("Progressbar_Refreshtransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving connection details....
        /// </summary>
        public static string Progressbar_Savingconnection {
            get {
                return ResourceManager.GetString("Progressbar_Savingconnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating credentials....
        /// </summary>
        public static string Progressbar_Validatingcredentials {
            get {
                return ResourceManager.GetString("Progressbar_Validatingcredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sage Mobile Sales.
        /// </summary>
        public static string Sage_MobileSales {
            get {
                return ResourceManager.GetString("Sage_MobileSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Settings.
        /// </summary>
        public static string Settings_ClearSettings {
            get {
                return ResourceManager.GetString("Settings_ClearSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Settings.
        /// </summary>
        public static string Settings_ClearSettingsToolTip {
            get {
                return ResourceManager.GetString("Settings_ClearSettingsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Details.
        /// </summary>
        public static string Settings_ConnectionDetails {
            get {
                return ResourceManager.GetString("Settings_ConnectionDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter information to connect to your accounting or ERP system..
        /// </summary>
        public static string Settings_ConnectionsMessage {
            get {
                return ResourceManager.GetString("Settings_ConnectionsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Settings.
        /// </summary>
        public static string Settings_EditSettings {
            get {
                return ResourceManager.GetString("Settings_EditSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Settings.
        /// </summary>
        public static string Settings_EditSettingsToolTip {
            get {
                return ResourceManager.GetString("Settings_EditSettingsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Transaction Settings.
        /// </summary>
        public static string Settings_FeatureHeader {
            get {
                return ResourceManager.GetString("Settings_FeatureHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify transaction settings for your accounting or ERP system..
        /// </summary>
        public static string Settings_FeatureMessage {
            get {
                return ResourceManager.GetString("Settings_FeatureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More.
        /// </summary>
        public static string Settings_LearnMore {
            get {
                return ResourceManager.GetString("Settings_LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Site:.
        /// </summary>
        public static string Settings_Name {
            get {
                return ResourceManager.GetString("Settings_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sage Data Cloud Connector did not find a supported version of Sage accounting or ERP software on your computer. Before setting up Sage Data Cloud Connector, you must install supported accounting or ERP software or apply required product updates to your installed software..
        /// </summary>
        public static string SignIn_BackofficeMissing {
            get {
                return ResourceManager.GetString("SignIn_BackofficeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported Accounting/ERP Software Not Found.
        /// </summary>
        public static string SignIn_BackofficeMissing_Header {
            get {
                return ResourceManager.GetString("SignIn_BackofficeMissing_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Started Help.
        /// </summary>
        public static string SignIn_Gettingstarted {
            get {
                return ResourceManager.GetString("SignIn_Gettingstarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sage Data Cloud Connector transfers data between your accounting or ERP software and your Sage web and mobile applications..
        /// </summary>
        public static string SignIn_Header1 {
            get {
                return ResourceManager.GetString("SignIn_Header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To set up or manage your connections, sign in with your Sage ID..
        /// </summary>
        public static string SignIn_Header2 {
            get {
                return ResourceManager.GetString("SignIn_Header2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string SignIn_SinginButtoncaption {
            get {
                return ResourceManager.GetString("SignIn_SinginButtoncaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to Open Sage Mobile Sales.
        /// </summary>
        public static string ToolTip_MonitorIcon {
            get {
                return ResourceManager.GetString("ToolTip_MonitorIcon", resourceCulture);
            }
        }
    }
}
