//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SageConnect.ViewModels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SageConnect_ViewModels_HelpLinks_NonProduction {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SageConnect_ViewModels_HelpLinks_NonProduction() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SageConnect.ViewModels.SageConnect.ViewModels.HelpLinks.NonProduction", typeof(SageConnect_ViewModels_HelpLinks_NonProduction).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://help.connector.sageinternal.com/en-us/web/win/index.htm#cshid=7.
        /// </summary>
        public static string ConfirmationDialog_ClearSettingsHelp {
            get {
                return ResourceManager.GetString("ConfirmationDialog_ClearSettingsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://help.connector.sageinternal.com/en-us/web/win/index.htm#cshid=1.
        /// </summary>
        public static string Connetion_HelpFile {
            get {
                return ResourceManager.GetString("Connetion_HelpFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://help.connector.sageinternal.com/en-us/web/win/index.htm#cshid=9.
        /// </summary>
        public static string ErrorMessage_CloudRegistratoinFailed_HelpUri {
            get {
                return ResourceManager.GetString("ErrorMessage_CloudRegistratoinFailed_HelpUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://help.connector.sageinternal.com/en-us/web/win/index.htm#cshid=8.
        /// </summary>
        public static string ErrorMessage_FeatureConfigValueMissing_HelpUri {
            get {
                return ResourceManager.GetString("ErrorMessage_FeatureConfigValueMissing_HelpUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://help.connector.sageinternal.com/en-us/web/win/index.htm#cshid=5.
        /// </summary>
        public static string ErrorMessage_HyperLink_NoTenant {
            get {
                return ResourceManager.GetString("ErrorMessage_HyperLink_NoTenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://help.connector.sageinternal.com/en-us/web/win/index.htm#cshid=3.
        /// </summary>
        public static string Features_Helpfile_English {
            get {
                return ResourceManager.GetString("Features_Helpfile_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://help.connector.sageinternal.com/en-us/web/win/index.htm#cshid=2.
        /// </summary>
        public static string Settings_Helpfile_English {
            get {
                return ResourceManager.GetString("Settings_Helpfile_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://help.connector.sageinternal.com/en-us/web/win/index.htm#cshid=6.
        /// </summary>
        public static string Signin_GettingstartedHelpUri {
            get {
                return ResourceManager.GetString("Signin_GettingstartedHelpUri", resourceCulture);
            }
        }
    }
}
