//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Sage.Connector.PremiseStore.ConfigurationStore
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    internal partial class ConfigurationStoreModelContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ConfigurationStoreModelContainer object using the connection string found in the 'ConfigurationStoreModelContainer' section of the application configuration file.
        /// </summary>
        public ConfigurationStoreModelContainer() : base("name=ConfigurationStoreModelContainer", "ConfigurationStoreModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ConfigurationStoreModelContainer object.
        /// </summary>
        public ConfigurationStoreModelContainer(string connectionString) : base(connectionString, "ConfigurationStoreModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ConfigurationStoreModelContainer object.
        /// </summary>
        public ConfigurationStoreModelContainer(EntityConnection connection) : base(connection, "ConfigurationStoreModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PremiseConfiguration> PremiseConfigurations
        {
            get
            {
                if ((_PremiseConfigurations == null))
                {
                    _PremiseConfigurations = base.CreateObjectSet<PremiseConfiguration>("PremiseConfigurations");
                }
                return _PremiseConfigurations;
            }
        }
        private ObjectSet<PremiseConfiguration> _PremiseConfigurations;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PremiseConfigurations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPremiseConfigurations(PremiseConfiguration premiseConfiguration)
        {
            base.AddObject("PremiseConfigurations", premiseConfiguration);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ConfigurationStoreModel", Name="PremiseConfiguration")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PremiseConfiguration : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PremiseConfiguration object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="backOfficeCompanyUniqueId">Initial value of the BackOfficeCompanyUniqueId property.</param>
        /// <param name="premiseAgent">Initial value of the PremiseAgent property.</param>
        /// <param name="cloudTenantId">Initial value of the CloudTenantId property.</param>
        /// <param name="cloudPremiseKey">Initial value of the CloudPremiseKey property.</param>
        /// <param name="siteAddress">Initial value of the SiteAddress property.</param>
        /// <param name="backOfficeConnectionEnabledToReceive">Initial value of the BackOfficeConnectionEnabledToReceive property.</param>
        /// <param name="cloudConnectionEnabledToReceive">Initial value of the CloudConnectionEnabledToReceive property.</param>
        /// <param name="cloudConnectionEnabledToSend">Initial value of the CloudConnectionEnabledToSend property.</param>
        /// <param name="sentDocumentStoragePolicy">Initial value of the SentDocumentStoragePolicy property.</param>
        /// <param name="sentDocumentStorageDays">Initial value of the SentDocumentStorageDays property.</param>
        /// <param name="sentDocumentStorageMBs">Initial value of the SentDocumentStorageMBs property.</param>
        /// <param name="sentDocumentFolderName">Initial value of the SentDocumentFolderName property.</param>
        /// <param name="backOfficeAllowableConcurrentExecutions">Initial value of the BackOfficeAllowableConcurrentExecutions property.</param>
        /// <param name="connectorPluginId">Initial value of the ConnectorPluginId property.</param>
        /// <param name="backOfficeProductName">Initial value of the BackOfficeProductName property.</param>
        /// <param name="backOfficeConnectionCredentials">Initial value of the BackOfficeConnectionCredentials property.</param>
        public static PremiseConfiguration CreatePremiseConfiguration(global::System.Guid id, global::System.String backOfficeCompanyUniqueId, global::System.String premiseAgent, global::System.String cloudTenantId, global::System.String cloudPremiseKey, global::System.String siteAddress, global::System.Boolean backOfficeConnectionEnabledToReceive, global::System.Boolean cloudConnectionEnabledToReceive, global::System.Boolean cloudConnectionEnabledToSend, global::System.Int16 sentDocumentStoragePolicy, global::System.Int16 sentDocumentStorageDays, global::System.Int64 sentDocumentStorageMBs, global::System.String sentDocumentFolderName, global::System.Int16 backOfficeAllowableConcurrentExecutions, global::System.String connectorPluginId, global::System.String backOfficeProductName, global::System.String backOfficeConnectionCredentials)
        {
            PremiseConfiguration premiseConfiguration = new PremiseConfiguration();
            premiseConfiguration.Id = id;
            premiseConfiguration.BackOfficeCompanyUniqueId = backOfficeCompanyUniqueId;
            premiseConfiguration.PremiseAgent = premiseAgent;
            premiseConfiguration.CloudTenantId = cloudTenantId;
            premiseConfiguration.CloudPremiseKey = cloudPremiseKey;
            premiseConfiguration.SiteAddress = siteAddress;
            premiseConfiguration.BackOfficeConnectionEnabledToReceive = backOfficeConnectionEnabledToReceive;
            premiseConfiguration.CloudConnectionEnabledToReceive = cloudConnectionEnabledToReceive;
            premiseConfiguration.CloudConnectionEnabledToSend = cloudConnectionEnabledToSend;
            premiseConfiguration.SentDocumentStoragePolicy = sentDocumentStoragePolicy;
            premiseConfiguration.SentDocumentStorageDays = sentDocumentStorageDays;
            premiseConfiguration.SentDocumentStorageMBs = sentDocumentStorageMBs;
            premiseConfiguration.SentDocumentFolderName = sentDocumentFolderName;
            premiseConfiguration.BackOfficeAllowableConcurrentExecutions = backOfficeAllowableConcurrentExecutions;
            premiseConfiguration.ConnectorPluginId = connectorPluginId;
            premiseConfiguration.BackOfficeProductName = backOfficeProductName;
            premiseConfiguration.BackOfficeConnectionCredentials = backOfficeConnectionCredentials;
            return premiseConfiguration;
        }

        /// <summary>
        /// Creates the premise configuration. 
        /// </summary>
        /// <returns></returns>
        /// <remarks>manually added to work around code generation failures in EF4.x</remarks>
        public static PremiseConfiguration CreatePremiseConfiguration()
        {
            PremiseConfiguration premiseConfiguration = new PremiseConfiguration();
            return premiseConfiguration;
        }
        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BackOfficeCompanyUniqueId
        {
            get
            {
                return _BackOfficeCompanyUniqueId;
            }
            set
            {
                OnBackOfficeCompanyUniqueIdChanging(value);
                ReportPropertyChanging("BackOfficeCompanyUniqueId");
                _BackOfficeCompanyUniqueId = StructuralObject.SetValidValue(value, false, "BackOfficeCompanyUniqueId");
                ReportPropertyChanged("BackOfficeCompanyUniqueId");
                OnBackOfficeCompanyUniqueIdChanged();
            }
        }
        private global::System.String _BackOfficeCompanyUniqueId;
        partial void OnBackOfficeCompanyUniqueIdChanging(global::System.String value);
        partial void OnBackOfficeCompanyUniqueIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PremiseAgent
        {
            get
            {
                return _PremiseAgent;
            }
            set
            {
                OnPremiseAgentChanging(value);
                ReportPropertyChanging("PremiseAgent");
                _PremiseAgent = StructuralObject.SetValidValue(value, false, "PremiseAgent");
                ReportPropertyChanged("PremiseAgent");
                OnPremiseAgentChanged();
            }
        }
        private global::System.String _PremiseAgent;
        partial void OnPremiseAgentChanging(global::System.String value);
        partial void OnPremiseAgentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CloudTenantId
        {
            get
            {
                return _CloudTenantId;
            }
            set
            {
                OnCloudTenantIdChanging(value);
                ReportPropertyChanging("CloudTenantId");
                _CloudTenantId = StructuralObject.SetValidValue(value, false, "CloudTenantId");
                ReportPropertyChanged("CloudTenantId");
                OnCloudTenantIdChanged();
            }
        }
        private global::System.String _CloudTenantId;
        partial void OnCloudTenantIdChanging(global::System.String value);
        partial void OnCloudTenantIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CloudPremiseKey
        {
            get
            {
                return _CloudPremiseKey;
            }
            set
            {
                OnCloudPremiseKeyChanging(value);
                ReportPropertyChanging("CloudPremiseKey");
                _CloudPremiseKey = StructuralObject.SetValidValue(value, false, "CloudPremiseKey");
                ReportPropertyChanged("CloudPremiseKey");
                OnCloudPremiseKeyChanged();
            }
        }
        private global::System.String _CloudPremiseKey;
        partial void OnCloudPremiseKeyChanging(global::System.String value);
        partial void OnCloudPremiseKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CloudTenantClaim
        {
            get
            {
                return _CloudTenantClaim;
            }
            set
            {
                OnCloudTenantClaimChanging(value);
                ReportPropertyChanging("CloudTenantClaim");
                _CloudTenantClaim = StructuralObject.SetValidValue(value, true, "CloudTenantClaim");
                ReportPropertyChanged("CloudTenantClaim");
                OnCloudTenantClaimChanged();
            }
        }
        private global::System.String _CloudTenantClaim;
        partial void OnCloudTenantClaimChanging(global::System.String value);
        partial void OnCloudTenantClaimChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SiteAddress
        {
            get
            {
                return _SiteAddress;
            }
            set
            {
                OnSiteAddressChanging(value);
                ReportPropertyChanging("SiteAddress");
                _SiteAddress = StructuralObject.SetValidValue(value, false, "SiteAddress");
                ReportPropertyChanged("SiteAddress");
                OnSiteAddressChanged();
            }
        }
        private global::System.String _SiteAddress;
        partial void OnSiteAddressChanging(global::System.String value);
        partial void OnSiteAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean BackOfficeConnectionEnabledToReceive
        {
            get
            {
                return _BackOfficeConnectionEnabledToReceive;
            }
            set
            {
                OnBackOfficeConnectionEnabledToReceiveChanging(value);
                ReportPropertyChanging("BackOfficeConnectionEnabledToReceive");
                _BackOfficeConnectionEnabledToReceive = StructuralObject.SetValidValue(value, "BackOfficeConnectionEnabledToReceive");
                ReportPropertyChanged("BackOfficeConnectionEnabledToReceive");
                OnBackOfficeConnectionEnabledToReceiveChanged();
            }
        }
        private global::System.Boolean _BackOfficeConnectionEnabledToReceive;
        partial void OnBackOfficeConnectionEnabledToReceiveChanging(global::System.Boolean value);
        partial void OnBackOfficeConnectionEnabledToReceiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean CloudConnectionEnabledToReceive
        {
            get
            {
                return _CloudConnectionEnabledToReceive;
            }
            set
            {
                OnCloudConnectionEnabledToReceiveChanging(value);
                ReportPropertyChanging("CloudConnectionEnabledToReceive");
                _CloudConnectionEnabledToReceive = StructuralObject.SetValidValue(value, "CloudConnectionEnabledToReceive");
                ReportPropertyChanged("CloudConnectionEnabledToReceive");
                OnCloudConnectionEnabledToReceiveChanged();
            }
        }
        private global::System.Boolean _CloudConnectionEnabledToReceive;
        partial void OnCloudConnectionEnabledToReceiveChanging(global::System.Boolean value);
        partial void OnCloudConnectionEnabledToReceiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean CloudConnectionEnabledToSend
        {
            get
            {
                return _CloudConnectionEnabledToSend;
            }
            set
            {
                OnCloudConnectionEnabledToSendChanging(value);
                ReportPropertyChanging("CloudConnectionEnabledToSend");
                _CloudConnectionEnabledToSend = StructuralObject.SetValidValue(value, "CloudConnectionEnabledToSend");
                ReportPropertyChanged("CloudConnectionEnabledToSend");
                OnCloudConnectionEnabledToSendChanged();
            }
        }
        private global::System.Boolean _CloudConnectionEnabledToSend;
        partial void OnCloudConnectionEnabledToSendChanging(global::System.Boolean value);
        partial void OnCloudConnectionEnabledToSendChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CloudCompanyUrl
        {
            get
            {
                return _CloudCompanyUrl;
            }
            set
            {
                OnCloudCompanyUrlChanging(value);
                ReportPropertyChanging("CloudCompanyUrl");
                _CloudCompanyUrl = StructuralObject.SetValidValue(value, true, "CloudCompanyUrl");
                ReportPropertyChanged("CloudCompanyUrl");
                OnCloudCompanyUrlChanged();
            }
        }
        private global::System.String _CloudCompanyUrl;
        partial void OnCloudCompanyUrlChanging(global::System.String value);
        partial void OnCloudCompanyUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CloudCompanyName
        {
            get
            {
                return _CloudCompanyName;
            }
            set
            {
                OnCloudCompanyNameChanging(value);
                ReportPropertyChanging("CloudCompanyName");
                _CloudCompanyName = StructuralObject.SetValidValue(value, true, "CloudCompanyName");
                ReportPropertyChanged("CloudCompanyName");
                OnCloudCompanyNameChanged();
            }
        }
        private global::System.String _CloudCompanyName;
        partial void OnCloudCompanyNameChanging(global::System.String value);
        partial void OnCloudCompanyNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BackOfficeCompanyName
        {
            get
            {
                return _BackOfficeCompanyName;
            }
            set
            {
                OnBackOfficeCompanyNameChanging(value);
                ReportPropertyChanging("BackOfficeCompanyName");
                _BackOfficeCompanyName = StructuralObject.SetValidValue(value, true, "BackOfficeCompanyName");
                ReportPropertyChanged("BackOfficeCompanyName");
                OnBackOfficeCompanyNameChanged();
            }
        }
        private global::System.String _BackOfficeCompanyName;
        partial void OnBackOfficeCompanyNameChanging(global::System.String value);
        partial void OnBackOfficeCompanyNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 SentDocumentStoragePolicy
        {
            get
            {
                return _SentDocumentStoragePolicy;
            }
            set
            {
                OnSentDocumentStoragePolicyChanging(value);
                ReportPropertyChanging("SentDocumentStoragePolicy");
                _SentDocumentStoragePolicy = StructuralObject.SetValidValue(value, "SentDocumentStoragePolicy");
                ReportPropertyChanged("SentDocumentStoragePolicy");
                OnSentDocumentStoragePolicyChanged();
            }
        }
        private global::System.Int16 _SentDocumentStoragePolicy;
        partial void OnSentDocumentStoragePolicyChanging(global::System.Int16 value);
        partial void OnSentDocumentStoragePolicyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 SentDocumentStorageDays
        {
            get
            {
                return _SentDocumentStorageDays;
            }
            set
            {
                OnSentDocumentStorageDaysChanging(value);
                ReportPropertyChanging("SentDocumentStorageDays");
                _SentDocumentStorageDays = StructuralObject.SetValidValue(value, "SentDocumentStorageDays");
                ReportPropertyChanged("SentDocumentStorageDays");
                OnSentDocumentStorageDaysChanged();
            }
        }
        private global::System.Int16 _SentDocumentStorageDays;
        partial void OnSentDocumentStorageDaysChanging(global::System.Int16 value);
        partial void OnSentDocumentStorageDaysChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 SentDocumentStorageMBs
        {
            get
            {
                return _SentDocumentStorageMBs;
            }
            set
            {
                OnSentDocumentStorageMBsChanging(value);
                ReportPropertyChanging("SentDocumentStorageMBs");
                _SentDocumentStorageMBs = StructuralObject.SetValidValue(value, "SentDocumentStorageMBs");
                ReportPropertyChanged("SentDocumentStorageMBs");
                OnSentDocumentStorageMBsChanged();
            }
        }
        private global::System.Int64 _SentDocumentStorageMBs;
        partial void OnSentDocumentStorageMBsChanging(global::System.Int64 value);
        partial void OnSentDocumentStorageMBsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SentDocumentFolderName
        {
            get
            {
                return _SentDocumentFolderName;
            }
            set
            {
                OnSentDocumentFolderNameChanging(value);
                ReportPropertyChanging("SentDocumentFolderName");
                _SentDocumentFolderName = StructuralObject.SetValidValue(value, false, "SentDocumentFolderName");
                ReportPropertyChanged("SentDocumentFolderName");
                OnSentDocumentFolderNameChanged();
            }
        }
        private global::System.String _SentDocumentFolderName;
        partial void OnSentDocumentFolderNameChanging(global::System.String value);
        partial void OnSentDocumentFolderNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 BackOfficeAllowableConcurrentExecutions
        {
            get
            {
                return _BackOfficeAllowableConcurrentExecutions;
            }
            set
            {
                OnBackOfficeAllowableConcurrentExecutionsChanging(value);
                ReportPropertyChanging("BackOfficeAllowableConcurrentExecutions");
                _BackOfficeAllowableConcurrentExecutions = StructuralObject.SetValidValue(value, "BackOfficeAllowableConcurrentExecutions");
                ReportPropertyChanged("BackOfficeAllowableConcurrentExecutions");
                OnBackOfficeAllowableConcurrentExecutionsChanged();
            }
        }
        private global::System.Int16 _BackOfficeAllowableConcurrentExecutions;
        partial void OnBackOfficeAllowableConcurrentExecutionsChanging(global::System.Int16 value);
        partial void OnBackOfficeAllowableConcurrentExecutionsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MinCommunicationFailureRetryInterval
        {
            get
            {
                return _MinCommunicationFailureRetryInterval;
            }
            set
            {
                OnMinCommunicationFailureRetryIntervalChanging(value);
                ReportPropertyChanging("MinCommunicationFailureRetryInterval");
                _MinCommunicationFailureRetryInterval = StructuralObject.SetValidValue(value, "MinCommunicationFailureRetryInterval");
                ReportPropertyChanged("MinCommunicationFailureRetryInterval");
                OnMinCommunicationFailureRetryIntervalChanged();
            }
        }
        private global::System.Int32 _MinCommunicationFailureRetryInterval = 60000;
        partial void OnMinCommunicationFailureRetryIntervalChanging(global::System.Int32 value);
        partial void OnMinCommunicationFailureRetryIntervalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MaxCommunicationFailureRetryInterval
        {
            get
            {
                return _MaxCommunicationFailureRetryInterval;
            }
            set
            {
                OnMaxCommunicationFailureRetryIntervalChanging(value);
                ReportPropertyChanging("MaxCommunicationFailureRetryInterval");
                _MaxCommunicationFailureRetryInterval = StructuralObject.SetValidValue(value, "MaxCommunicationFailureRetryInterval");
                ReportPropertyChanged("MaxCommunicationFailureRetryInterval");
                OnMaxCommunicationFailureRetryIntervalChanged();
            }
        }
        private global::System.Int32 _MaxCommunicationFailureRetryInterval = 300000;
        partial void OnMaxCommunicationFailureRetryIntervalChanging(global::System.Int32 value);
        partial void OnMaxCommunicationFailureRetryIntervalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ConnectorPluginId
        {
            get
            {
                return _ConnectorPluginId;
            }
            set
            {
                OnConnectorPluginIdChanging(value);
                ReportPropertyChanging("ConnectorPluginId");
                _ConnectorPluginId = StructuralObject.SetValidValue(value, false, "ConnectorPluginId");
                ReportPropertyChanged("ConnectorPluginId");
                OnConnectorPluginIdChanged();
            }
        }
        private global::System.String _ConnectorPluginId;
        partial void OnConnectorPluginIdChanging(global::System.String value);
        partial void OnConnectorPluginIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BackOfficeProductName
        {
            get
            {
                return _BackOfficeProductName;
            }
            set
            {
                OnBackOfficeProductNameChanging(value);
                ReportPropertyChanging("BackOfficeProductName");
                _BackOfficeProductName = StructuralObject.SetValidValue(value, false, "BackOfficeProductName");
                ReportPropertyChanged("BackOfficeProductName");
                OnBackOfficeProductNameChanged();
            }
        }
        private global::System.String _BackOfficeProductName;
        partial void OnBackOfficeProductNameChanging(global::System.String value);
        partial void OnBackOfficeProductNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BackOfficeConnectionCredentials
        {
            get
            {
                return _BackOfficeConnectionCredentials;
            }
            set
            {
                OnBackOfficeConnectionCredentialsChanging(value);
                ReportPropertyChanging("BackOfficeConnectionCredentials");
                _BackOfficeConnectionCredentials = StructuralObject.SetValidValue(value, false, "BackOfficeConnectionCredentials");
                ReportPropertyChanged("BackOfficeConnectionCredentials");
                OnBackOfficeConnectionCredentialsChanged();
            }
        }
        private global::System.String _BackOfficeConnectionCredentials;
        partial void OnBackOfficeConnectionCredentialsChanging(global::System.String value);
        partial void OnBackOfficeConnectionCredentialsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BackOfficeConnectionCredentialsDescription
        {
            get
            {
                return _BackOfficeConnectionCredentialsDescription;
            }
            set
            {
                OnBackOfficeConnectionCredentialsDescriptionChanging(value);
                ReportPropertyChanging("BackOfficeConnectionCredentialsDescription");
                _BackOfficeConnectionCredentialsDescription = StructuralObject.SetValidValue(value, true, "BackOfficeConnectionCredentialsDescription");
                ReportPropertyChanged("BackOfficeConnectionCredentialsDescription");
                OnBackOfficeConnectionCredentialsDescriptionChanged();
            }
        }
        private global::System.String _BackOfficeConnectionCredentialsDescription;
        partial void OnBackOfficeConnectionCredentialsDescriptionChanging(global::System.String value);
        partial void OnBackOfficeConnectionCredentialsDescriptionChanged();

        #endregion

    }

    #endregion

}
