
// NOTE: this source file is GENERATED by the LibraryPreBuild LibraryConfig named action.
// DO NOT EDIT THIS FILE, IT IS NOT CHECKED IN TO SOURCE CONTROL!

//[assembly: AssemblyCompany("Sage Software, Inc.")]
//[assembly: AssemblyCopyright("© 2010 - 2014 Sage Software, Inc. All rights reserved.")]
//[assembly: AssemblyTrademark("© 2010 - 2014 Sage Software, Inc. All rights reserved.")]

//// AssemblyVersion and AssemblyInformationalVersion changes only by release
//[assembly: AssemblyVersion("1.0.0.0")]
//[assembly: AssemblyInformationalVersion("1.0.0.0")]
    