//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SageConnector.ViewModel {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesViewModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesViewModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SageConnector.ViewModel.ResourcesViewModel", typeof(ResourcesViewModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default_CSH.htm#10038.
        /// </summary>
        internal static string AccountSelectionFormHelpPathFragment {
            get {
                return ResourceManager.GetString("AccountSelectionFormHelpPathFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Blank {
            get {
                object obj = ResourceManager.GetObject("Blank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BlankLight {
            get {
                object obj = ResourceManager.GetObject("BlankLight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The website is temporarily unavailable. Please try again later..
        /// </summary>
        internal static string ConnectionDetail_CloudUnavailable {
            get {
                return ResourceManager.GetString("ConnectionDetail_CloudUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to the website..
        /// </summary>
        internal static string ConnectionDetail_CommunicationFailure {
            get {
                return ResourceManager.GetString("ConnectionDetail_CommunicationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The gateway service is unavailable. Verify that port 8443 is open in your firewall. If the port is open, the gateway service may be down temporarily. Please try again later..
        /// </summary>
        internal static string ConnectionDetail_GatewayServiceUnavailable {
            get {
                return ResourceManager.GetString("ConnectionDetail_GatewayServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sage Connector software is not compatible with the website. Please install a compatible version..
        /// </summary>
        internal static string ConnectionDetail_IncompatibleClient {
            get {
                return ResourceManager.GetString("ConnectionDetail_IncompatibleClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no internet connection. Please check with your system administrator..
        /// </summary>
        internal static string ConnectionDetail_InternetConnectionUnavailable {
            get {
                return ResourceManager.GetString("ConnectionDetail_InternetConnectionUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection information is not valid. Verify that the connection key on the site matches the connection key in the Sage Connector software..
        /// </summary>
        internal static string ConnectionDetail_InvalidConnectionInformation {
            get {
                return ResourceManager.GetString("ConnectionDetail_InvalidConnectionInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no local network available on this computer. Please check with your system administrator..
        /// </summary>
        internal static string ConnectionDetail_LocalNetworkUnavailable {
            get {
                return ResourceManager.GetString("ConnectionDetail_LocalNetworkUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine website connectivity. The site URL used by the Sage Connector may not match the actual website URL..
        /// </summary>
        internal static string ConnectionDetail_None {
            get {
                return ResourceManager.GetString("ConnectionDetail_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Sage Connector is communicating successfully with the website..
        /// </summary>
        internal static string ConnectionDetail_Normal {
            get {
                return ResourceManager.GetString("ConnectionDetail_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New connection information is needed. This will be retrieved automatically..
        /// </summary>
        internal static string ConnectionDetail_Reconfigure {
            get {
                return ResourceManager.GetString("ConnectionDetail_Reconfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This site has been suspended by Sage..
        /// </summary>
        internal static string ConnectionDetail_TenantDisabled {
            get {
                return ResourceManager.GetString("ConnectionDetail_TenantDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The company database is in use for an existing connection..
        /// </summary>
        internal static string ConnectorDetails_CompanyDatabaseInUse {
            get {
                return ResourceManager.GetString("ConnectorDetails_CompanyDatabaseInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data access problem has occured..
        /// </summary>
        internal static string ConnectorDetails_ConfigurationDataProblem {
            get {
                return ResourceManager.GetString("ConnectorDetails_ConfigurationDataProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This connection key is already in use..
        /// </summary>
        internal static string ConnectorDetails_ConnectionKeyInUse {
            get {
                return ResourceManager.GetString("ConnectorDetails_ConnectionKeyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred communicating with the website {0}..
        /// </summary>
        internal static string ConnectorDetails_MessagingServiceNotAvailableException {
            get {
                return ResourceManager.GetString("ConnectorDetails_MessagingServiceNotAvailableException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiredFieldMissing.
        /// </summary>
        internal static string ConnectorDetails_RequiredFieldErrorCaption {
            get {
                return ResourceManager.GetString("ConnectorDetails_RequiredFieldErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is required..
        /// </summary>
        internal static string ConnectorDetails_RequiredFieldsErrorMessage {
            get {
                return ResourceManager.GetString("ConnectorDetails_RequiredFieldsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection key is for a website which is already in use..
        /// </summary>
        internal static string ConnectorDetails_TenantIdAlreadyInUse {
            get {
                return ResourceManager.GetString("ConnectorDetails_TenantIdAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This connection key does not match the existing web site.  Please create a new connection to use this key..
        /// </summary>
        internal static string ConnectorDetails_TenantIdDoesNotMatchSpecifiedWebsite {
            get {
                return ResourceManager.GetString("ConnectorDetails_TenantIdDoesNotMatchSpecifiedWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection key for the website does not match the connection key in the Sage Connector connection. Please delete the connection in the Sage connector and recreate the connection using the correct connection key from the website.
        /// </summary>
        internal static string ConnectorDetails_ToChangeWebsiteCreateNewConnection {
            get {
                return ResourceManager.GetString("ConnectorDetails_ToChangeWebsiteCreateNewConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error response was received from the back office..
        /// </summary>
        internal static string ConnectorLogin_DefaultErrorResponseFromBackoffice {
            get {
                return ResourceManager.GetString("ConnectorLogin_DefaultErrorResponseFromBackoffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login validation did not succeed..
        /// </summary>
        internal static string ConnectorLogin_LoginError_BackofficeValidationDidNotSucceed {
            get {
                return ResourceManager.GetString("ConnectorLogin_LoginError_BackofficeValidationDidNotSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No response received from the back office..
        /// </summary>
        internal static string ConnectorLogin_NoResponseFromBackoffice {
            get {
                return ResourceManager.GetString("ConnectorLogin_NoResponseFromBackoffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string ConnectorRequestList_CompletedStatusText {
            get {
                return ResourceManager.GetString("ConnectorRequestList_CompletedStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed with Error.
        /// </summary>
        internal static string ConnectorRequestList_CompletedWithErrorStatusText {
            get {
                return ResourceManager.GetString("ConnectorRequestList_CompletedWithErrorStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        internal static string ConnectorRequestList_InProgressStatusText {
            get {
                return ResourceManager.GetString("ConnectorRequestList_InProgressStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} service is not currently enabled on this computer.\n\nEnable the service in the Services control panel and then click OK to continue configuring the {1}\n\nFor information on enabling services, refer to Microsoft Windows documentation..
        /// </summary>
        internal static string ConnectorServiceNotEnabledMessageFormat {
            get {
                return ResourceManager.GetString("ConnectorServiceNotEnabledMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default_CSH.htm#10001.
        /// </summary>
        internal static string DetailFormHelpPathFragment {
            get {
                return ResourceManager.GetString("DetailFormHelpPathFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GreenLight {
            get {
                object obj = ResourceManager.GetObject("GreenLight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default_CSH.htm#10000.
        /// </summary>
        internal static string MainFormHelpPathFragment {
            get {
                return ResourceManager.GetString("MainFormHelpPathFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RedLight {
            get {
                object obj = ResourceManager.GetObject("RedLight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default_CSH.htm#10037.
        /// </summary>
        internal static string RequestsFormHelpPathFragment {
            get {
                return ResourceManager.GetString("RequestsFormHelpPathFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Running {
            get {
                object obj = ResourceManager.GetObject("Running", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default_CSH.htm#10023.
        /// </summary>
        internal static string SystemRequirementsHelpPathFragment {
            get {
                return ResourceManager.GetString("SystemRequirementsHelpPathFragment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhiteLight {
            get {
                object obj = ResourceManager.GetObject("WhiteLight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
