//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Sage.Connector.PremiseStore.QueueStore
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    internal partial class QueueStoreModelContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new QueueStoreModelContainer object using the connection string found in the 'QueueStoreModelContainer' section of the application configuration file.
        /// </summary>
        public QueueStoreModelContainer() : base("name=QueueStoreModelContainer", "QueueStoreModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QueueStoreModelContainer object.
        /// </summary>
        public QueueStoreModelContainer(string connectionString) : base(connectionString, "QueueStoreModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QueueStoreModelContainer object.
        /// </summary>
        public QueueStoreModelContainer(EntityConnection connection) : base(connection, "QueueStoreModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<QueueEntry> QueueEntries
        {
            get
            {
                if ((_QueueEntries == null))
                {
                    _QueueEntries = base.CreateObjectSet<QueueEntry>("QueueEntries");
                }
                return _QueueEntries;
            }
        }
        private ObjectSet<QueueEntry> _QueueEntries;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the QueueEntries EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToQueueEntries(QueueEntry queueEntry)
        {
            base.AddObject("QueueEntries", queueEntry);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QueueStoreModel", Name="QueueEntry")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class QueueEntry : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new QueueEntry object.
        /// </summary>
        /// <param name="queueId">Initial value of the QueueId property.</param>
        /// <param name="dateTimeUtc">Initial value of the DateTimeUtc property.</param>
        /// <param name="user">Initial value of the User property.</param>
        /// <param name="machine">Initial value of the Machine property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        /// <param name="processingExpirationDateTimeUtc">Initial value of the ProcessingExpirationDateTimeUtc property.</param>
        /// <param name="content">Initial value of the Content property.</param>
        public static QueueEntry CreateQueueEntry(global::System.Guid queueId, global::System.DateTime dateTimeUtc, global::System.String user, global::System.String machine, global::System.String type, global::System.DateTime processingExpirationDateTimeUtc, global::System.String content)
        {
            QueueEntry queueEntry = new QueueEntry();
            queueEntry.QueueId = queueId;
            queueEntry.DateTimeUtc = dateTimeUtc;
            queueEntry.User = user;
            queueEntry.Machine = machine;
            queueEntry.Type = type;
            queueEntry.ProcessingExpirationDateTimeUtc = processingExpirationDateTimeUtc;
            queueEntry.Content = content;
            return queueEntry;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid QueueId
        {
            get
            {
                return _QueueId;
            }
            set
            {
                if (_QueueId != value)
                {
                    OnQueueIdChanging(value);
                    ReportPropertyChanging("QueueId");
                    _QueueId = StructuralObject.SetValidValue(value, "QueueId");
                    ReportPropertyChanged("QueueId");
                    OnQueueIdChanged();
                }
            }
        }
        private global::System.Guid _QueueId;
        partial void OnQueueIdChanging(global::System.Guid value);
        partial void OnQueueIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateTimeUtc
        {
            get
            {
                return _DateTimeUtc;
            }
            set
            {
                OnDateTimeUtcChanging(value);
                ReportPropertyChanging("DateTimeUtc");
                _DateTimeUtc = StructuralObject.SetValidValue(value, "DateTimeUtc");
                ReportPropertyChanged("DateTimeUtc");
                OnDateTimeUtcChanged();
            }
        }
        private global::System.DateTime _DateTimeUtc;
        partial void OnDateTimeUtcChanging(global::System.DateTime value);
        partial void OnDateTimeUtcChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String User
        {
            get
            {
                return _User;
            }
            set
            {
                OnUserChanging(value);
                ReportPropertyChanging("User");
                _User = StructuralObject.SetValidValue(value, false, "User");
                ReportPropertyChanged("User");
                OnUserChanged();
            }
        }
        private global::System.String _User;
        partial void OnUserChanging(global::System.String value);
        partial void OnUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Machine
        {
            get
            {
                return _Machine;
            }
            set
            {
                OnMachineChanging(value);
                ReportPropertyChanging("Machine");
                _Machine = StructuralObject.SetValidValue(value, false, "Machine");
                ReportPropertyChanged("Machine");
                OnMachineChanged();
            }
        }
        private global::System.String _Machine;
        partial void OnMachineChanging(global::System.String value);
        partial void OnMachineChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, false, "Type");
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ProcessingExpirationDateTimeUtc
        {
            get
            {
                return _ProcessingExpirationDateTimeUtc;
            }
            set
            {
                OnProcessingExpirationDateTimeUtcChanging(value);
                ReportPropertyChanging("ProcessingExpirationDateTimeUtc");
                _ProcessingExpirationDateTimeUtc = StructuralObject.SetValidValue(value, "ProcessingExpirationDateTimeUtc");
                ReportPropertyChanged("ProcessingExpirationDateTimeUtc");
                OnProcessingExpirationDateTimeUtcChanged();
            }
        }
        private global::System.DateTime _ProcessingExpirationDateTimeUtc;
        partial void OnProcessingExpirationDateTimeUtcChanging(global::System.DateTime value);
        partial void OnProcessingExpirationDateTimeUtcChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Content
        {
            get
            {
                return _Content;
            }
            set
            {
                OnContentChanging(value);
                ReportPropertyChanging("Content");
                _Content = StructuralObject.SetValidValue(value, false, "Content");
                ReportPropertyChanged("Content");
                OnContentChanged();
            }
        }
        private global::System.String _Content;
        partial void OnContentChanging(global::System.String value);
        partial void OnContentChanged();

        #endregion

    }

    #endregion

}
