//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sage.Connector.ConnectorServiceCommon {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sage.Connector.ConnectorServiceCommon.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact List.
        /// </summary>
        internal static string ContactListRequestDisplayName {
            get {
                return ResourceManager.GetString("ContactListRequestDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Retrieval.
        /// </summary>
        internal static string GetLogRequestDisplayName {
            get {
                return ResourceManager.GetString("GetLogRequestDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metrics Retrieval.
        /// </summary>
        internal static string GetMetricsRequestDisplayname {
            get {
                return ResourceManager.GetString("GetMetricsRequestDisplayname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Check Verification.
        /// </summary>
        internal static string HealthCheckRequestDisplayName {
            get {
                return ResourceManager.GetString("HealthCheckRequestDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job List.
        /// </summary>
        internal static string JobListRequestDisplayName {
            get {
                return ResourceManager.GetString("JobListRequestDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop Back.
        /// </summary>
        internal static string LoopBackRequestDisplayName {
            get {
                return ResourceManager.GetString("LoopBackRequestDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Equipment Costs.
        /// </summary>
        internal static string PostEquipmentCostRequestDisplayName {
            get {
                return ResourceManager.GetString("PostEquipmentCostRequestDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Producction Units.
        /// </summary>
        internal static string PostProductionUnitRequestDisplayName {
            get {
                return ResourceManager.GetString("PostProductionUnitRequestDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Time Entries.
        /// </summary>
        internal static string PostTimeEntryRequestDisplayName {
            get {
                return ResourceManager.GetString("PostTimeEntryRequestDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report List.
        /// </summary>
        internal static string ReportDescriptorListRequestDisplayName {
            get {
                return ResourceManager.GetString("ReportDescriptorListRequestDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category List.
        /// </summary>
        internal static string Request_CategoryDisplayName {
            get {
                return ResourceManager.GetString("Request_CategoryDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certification List.
        /// </summary>
        internal static string Request_CertificationDisplayName {
            get {
                return ResourceManager.GetString("Request_CertificationDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Code List.
        /// </summary>
        internal static string Request_CostCodeDisplayName {
            get {
                return ResourceManager.GetString("Request_CostCodeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain Mediation.
        /// </summary>
        internal static string Request_DomainMediationDisplayName {
            get {
                return ResourceManager.GetString("Request_DomainMediationDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee List.
        /// </summary>
        internal static string Request_EmployeeDisplayName {
            get {
                return ResourceManager.GetString("Request_EmployeeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Cost Code List.
        /// </summary>
        internal static string Request_EquipmentCostCodeDisplayName {
            get {
                return ResourceManager.GetString("Request_EquipmentCostCodeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment List.
        /// </summary>
        internal static string Request_EquipmentDisplayName {
            get {
                return ResourceManager.GetString("Request_EquipmentDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Period List.
        /// </summary>
        internal static string Request_PayPeriodDisplayName {
            get {
                return ResourceManager.GetString("Request_PayPeriodDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Type List.
        /// </summary>
        internal static string Request_PayTypeDisplayName {
            get {
                return ResourceManager.GetString("Request_PayTypeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Job List.
        /// </summary>
        internal static string Request_SubJobDisplayName {
            get {
                return ResourceManager.GetString("Request_SubJobDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Report.
        /// </summary>
        internal static string RunReportRequestDisplayName {
            get {
                return ResourceManager.GetString("RunReportRequestDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Parameters Update.
        /// </summary>
        internal static string UpdateConfigParamRequestDisplayName {
            get {
                return ResourceManager.GetString("UpdateConfigParamRequestDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Parameter Update.
        /// </summary>
        internal static string UpdateSiteServiceInfoRequestDisplayName {
            get {
                return ResourceManager.GetString("UpdateSiteServiceInfoRequestDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor List.
        /// </summary>
        internal static string VendorListRequestDisplayName {
            get {
                return ResourceManager.GetString("VendorListRequestDisplayName", resourceCulture);
            }
        }
    }
}
