//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sage.Connector.MockCloudHostApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sage.Connector.MockCloudHostApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Id&quot;:null,&quot;Customer&quot;:{&quot;Id&quot;:null,&quot;ExternalId&quot;:&quot;MTAwMQ2&quot;},&quot;AmountPaid&quot;:550.0,&quot;TransactionDate&quot;:&quot;2014-03-29T22:48:23.4796978Z&quot;,&quot;Type&quot;:2,&quot;Reference&quot;:&quot;Ref 1001&quot;,&quot;AuthorizationCode&quot;:&quot;xyz&quot;,&quot;CreditCardLast4&quot;:&quot;1234&quot;,&quot;ExpirationMonth&quot;:&quot;05&quot;,&quot;ExpirationYear&quot;:&quot;2015&quot;,&quot;Details&quot;:[{&quot;Id&quot;:null,&quot;Invoice&quot;:{&quot;Id&quot;:null,&quot;ExternalId&quot;:&quot;SW52IDEwMDE1&quot;},&quot;AppliedAmount&quot;:550.0,&quot;ExternalId&quot;:null,&quot;ExternalReference&quot;:null,&quot;EntityStatus&quot;:0}],&quot;ExternalId&quot;:null,&quot;ExternalReference&quot;:null,&quot;EntityStatus&quot;:0}.
        /// </summary>
        internal static string PaymentPayload {
            get {
                return ResourceManager.GetString("PaymentPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;StatementDate&quot;:&quot;2014-02-17T23:51:47.240622Z&quot;,&quot;CustomerReferences&quot;:[{&quot;Id&quot;:&quot;9576e315-d93c-49eb-b4ee-ec62fdbd337d&quot;,&quot;ExternalId&quot;:&quot;MTAwMA2&quot;},{&quot;Id&quot;:&quot;11a75953-61a5-4f86-957d-4fb1caf8dab0&quot;,&quot;ExternalId&quot;:&quot;MTAwMQ2&quot;},{&quot;Id&quot;:&quot;13a9dbc0-ddb3-4e74-a3ba-ee45366f9781&quot;,&quot;ExternalId&quot;:&quot;MTAwMg2&quot;},{&quot;Id&quot;:&quot;93a4ea28-c94e-4edf-888c-349691a95adc&quot;,&quot;ExternalId&quot;:&quot;MTAwMw2&quot;},{&quot;Id&quot;:&quot;b9b711ff-c1db-4319-b601-dab4a31dea98&quot;,&quot;ExternalId&quot;:&quot;MTAwNA2&quot;},{&quot;Id&quot;:&quot;20bc29eb-0ada-464b-9b2c-4c0aed4db111&quot;,&quot;ExternalId&quot;:&quot;MTAwNQ2&quot;},{&quot;Id&quot;:&quot;e6ca6c13-545d-487f-979 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProcessStatementsPayload {
            get {
                return ResourceManager.GetString("ProcessStatementsPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Details&quot;:[{&quot;Id&quot;:&quot;2bf197f2-1d0f-4b82-ba4e-a97b1a153731&quot;,&quot;Quantity&quot;:0.0,&quot;Price&quot;:0.0,&quot;InventoryItem&quot;:{&quot;Id&quot;:&quot;36872960-6dfe-4691-99d6-a39eecbc4e1a&quot;,&quot;ExternalId&quot;:&quot;1000&quot;},&quot;ExternalId&quot;:null,&quot;ExternalReference&quot;:null,&quot;EntityStatus&quot;:0},{&quot;Id&quot;:&quot;70bf65a6-b196-478e-b708-b1c0eaa1419b&quot;,&quot;Quantity&quot;:1.0,&quot;Price&quot;:0.0,&quot;InventoryItem&quot;:{&quot;Id&quot;:&quot;13a9e09b-e015-49b0-a5e5-9510ac5d704e&quot;,&quot;ExternalId&quot;:&quot;1001&quot;},&quot;ExternalId&quot;:null,&quot;ExternalReference&quot;:null,&quot;EntityStatus&quot;:0},{&quot;Id&quot;:&quot;811794a6-17f4-4462-be5e-5d77734da26d&quot;,&quot;Quantity&quot;:2.0,&quot;Price&quot;:0. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SalesDocumentPayload {
            get {
                return ResourceManager.GetString("SalesDocumentPayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Id&quot;:&quot;f8a702f4-6bc1-4f60-b81a-9e080158dfc3&quot;,&quot;PONumber&quot;:&quot;PO1234&quot;,&quot;Description&quot;:&quot;WorkOrder Desc&quot;,&quot;Customer&quot;:{&quot;Id&quot;:&quot;e41656af-4364-4e6f-99a1-be3603749ecf&quot;,&quot;ExternalId&quot;:&quot;MTAwMQ2&quot;},&quot;ServiceDate&quot;:&quot;2014-03-02T23:01:26.9730674Z&quot;,&quot;ApprovedDate&quot;:&quot;2014-02-20T23:01:26.9720671Z&quot;,&quot;Approver&quot;:{&quot;FirstName&quot;:&quot;contactFirst&quot;,&quot;LastName&quot;:&quot;contactLast&quot;},&quot;Recipient&quot;:&quot;Joe Recipient&quot;,&quot;Note&quot;:&quot;Note for this work order to invoice&quot;,&quot;QuickCode&quot;:&quot;WO&quot;,&quot;ServiceEndDate&quot;:&quot;2014-01-31T23:01:26.9730674Z&quot;,&quot;CompletedDate&quot;:&quot;2014-03-22T23:01:26.97306 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WorkOrderPayload {
            get {
                return ResourceManager.GetString("WorkOrderPayload", resourceCulture);
            }
        }
    }
}
