//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ICREMessageService")]
internal interface ICREMessageService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICREMessageService/PremiseToCloudMessages", ReplyAction="http://tempuri.org/ICREMessageService/PremiseToCloudMessagesResponse")]
    bool PremiseToCloudMessages(string PremiseID, string PremiseToken, string[] Messages);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICREMessageService/CloudToPremiseMessages", ReplyAction="http://tempuri.org/ICREMessageService/CloudToPremiseMessagesResponse")]
    string[] CloudToPremiseMessages(string PremiseID, string PremiseToken);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
internal interface ICREMessageServiceChannel : ICREMessageService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
internal partial class CREMessageServiceClient : System.ServiceModel.ClientBase<ICREMessageService>, ICREMessageService
{
    
    public CREMessageServiceClient()
    {
    }
    
    public CREMessageServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CREMessageServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CREMessageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CREMessageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public bool PremiseToCloudMessages(string PremiseID, string PremiseToken, string[] Messages)
    {
        return base.Channel.PremiseToCloudMessages(PremiseID, PremiseToken, Messages);
    }
    
    public string[] CloudToPremiseMessages(string PremiseID, string PremiseToken)
    {
        return base.Channel.CloudToPremiseMessages(PremiseID, PremiseToken);
    }
}
